;
; File generated by cc65 v 2.18 - Git ece63f0
;
	.fopt		compiler,"cc65 v 2.18 - Git ece63f0"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_itoa
	.import		_strlen
	.export		_main

.segment	"RODATA"

_TEXT:
	.byte	$4E,$49,$47,$47,$41,$20,$48,$45,$49,$4C,$20,$48,$49,$54,$4C,$45
	.byte	$52,$21,$7E,$00
_PALETTE:
	.byte	$1F
	.byte	$20
	.byte	$20
	.byte	$20
L00D0:
	.byte	$20,$00

; ---------------------------------------------------------------
; void __near__ fwx_start (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_fwx_start: near

.segment	"CODE"

;
; static void fwx_start(void) { FWXCTRL = (unsigned char) FWX_CTRL_SS; }
;
	lda     #$01
	sta     $4019
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ fwx_stop (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_fwx_stop: near

.segment	"CODE"

;
; static void fwx_stop(void) { FWXCTRL = 0; }
;
	lda     #$00
	sta     $4019
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ fwx_write_u8 (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_fwx_write_u8: near

.segment	"CODE"

;
; static void fwx_write_u8(uint8_t v) {
;
	jsr     pusha
;
; FWXDATA = v;
;
	ldy     #$00
	lda     (sp),y
	sta     $401A
;
; FWXCTRL |= FWX_CTRL_CLK;
;
	lda     $4019
	ora     #$02
	sta     $4019
;
; }
;
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ fwx_read_u8 (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_fwx_read_u8: near

.segment	"CODE"

;
; FWXCTRL |= FWX_CTRL_CLK;
;
	lda     $4019
	ora     #$02
	sta     $4019
;
; return FWXDATA;
;
	ldx     #$00
	lda     $401A
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ vram_write_xy (unsigned int, unsigned int, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_vram_write_xy: near

.segment	"CODE"

;
; static void vram_write_xy(unsigned x, unsigned y, uint8_t data) {
;
	jsr     pusha
;
; uint16_t addr = 0x2000 | (x & 0x1f) | ((y & 0x1f) << 5);
;
	ldy     #$03
	lda     (sp),y
	and     #$1F
	sta     ptr1
	ldy     #$01
	lda     (sp),y
	ldx     #$00
	and     #$1F
	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     pushax
;
; PPU_ADDRESS = (addr & 0xff00) >> 8;
;
	ldy     #$01
	lda     (sp),y
	tax
	dey
	stx     $2006
;
; PPU_ADDRESS = addr & 0xff;
;
	lda     (sp),y
	sta     $2006
;
; PPU_DATA = data;
;
	ldy     #$02
	lda     (sp),y
	sta     $2007
;
; }
;
	jmp     incsp7

.endproc

; ---------------------------------------------------------------
; void __near__ vram_write_cstr (unsigned int, unsigned int, __near__ const unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_vram_write_cstr: near

.segment	"CODE"

;
; static void vram_write_cstr(unsigned x, unsigned y, const char *path) {
;
	jsr     pushax
;
; n = (unsigned) strlen(path);
;
	jsr     decsp4
	ldy     #$05
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     _strlen
	jsr     stax0sp
;
; for (i = 0; i < n; ++i) {
;
	ldy     #$02
	lda     #$00
	sta     (sp),y
	iny
	sta     (sp),y
L0063:	ldy     #$03
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$00
	cmp     (sp),y
	txa
	iny
	sbc     (sp),y
	bcs     L0064
;
; unsigned x1 = x + i;
;
	ldy     #$08
	lda     (sp),y
	ldy     #$02
	clc
	adc     (sp),y
	pha
	ldy     #$09
	lda     (sp),y
	ldy     #$03
	adc     (sp),y
	tax
	pla
	jsr     pushax
;
; if (x1 >= 32) {
;
	ldy     #$01
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	cmp     #$20
	txa
	sbc     #$00
	bcc     L006C
;
; break;
;
	jsr     incsp2
	jmp     L0064
;
; vram_write_xy(x1, y, (uint8_t) path[i]);
;
L006C:	jsr     decsp4
	ldy     #$05
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$02
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	ldy     #$0D
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$00
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	ldy     #$0A
	lda     (sp),y
	ldy     #$08
	clc
	adc     (sp),y
	sta     ptr1
	ldy     #$0B
	lda     (sp),y
	ldy     #$09
	adc     (sp),y
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	jsr     _vram_write_xy
;
; }
;
	jsr     incsp2
;
; for (i = 0; i < n; ++i) {
;
	ldy     #$02
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	jmp     L0063
;
; }
;
L0064:	ldy     #$0A
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"BSS"

L0074:
	.res	2,$00
L0076:
	.res	256,$00
L0078:
	.res	3,$00

.segment	"CODE"

;
; unsigned filename_len = 0;
;
	jsr     decsp4
	jsr     push0
;
; PPU_CTRL = 0x00;
;
	jsr     decsp1
	sta     $2000
;
; PPU_MASK = 0x00;
;
	sta     $2001
;
; PPU_ADDRESS = 0x3f;
;
	lda     #$3F
	sta     $2006
;
; PPU_ADDRESS = 0x00;
;
	lda     #$00
	sta     $2006
;
; for (i = 0; i < sizeof(PALETTE); ++i) {
;
	ldy     #$05
	sta     (sp),y
	iny
	sta     (sp),y
L0086:	ldy     #$06
	lda     (sp),y
	cmp     #$00
	bne     L008E
	dey
	lda     (sp),y
	cmp     #$04
L008E:	bcs     L0087
;
; PPU_DATA = PALETTE[i];
;
	lda     #<(_PALETTE)
	ldy     #$05
	clc
	adc     (sp),y
	sta     ptr1
	lda     #>(_PALETTE)
	iny
	adc     (sp),y
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	sta     $2007
;
; for (i = 0; i < sizeof(PALETTE); ++i) {
;
	ldy     #$05
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	jmp     L0086
;
; for (i = 0; i < 30; ++i) {
;
L0087:	ldy     #$05
	lda     #$00
	sta     (sp),y
	iny
	sta     (sp),y
L0094:	ldy     #$06
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	cmp     #$1E
	txa
	sbc     #$00
	bvc     L009B
	eor     #$80
L009B:	bpl     L0095
;
; for (j = 0; j < 32; ++j) {
;
	ldy     #$03
	lda     #$00
	sta     (sp),y
	iny
	sta     (sp),y
L009D:	ldy     #$04
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	cmp     #$20
	txa
	sbc     #$00
	bvc     L00A4
	eor     #$80
L00A4:	bpl     L0096
;
; vram_write_xy(j, i, (uint8_t) ' ');
;
	jsr     decsp4
	ldy     #$08
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$02
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	ldy     #$0A
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$00
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     #$20
	jsr     _vram_write_xy
;
; for (j = 0; j < 32; ++j) {
;
	ldy     #$03
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	jmp     L009D
;
; for (i = 0; i < 30; ++i) {
;
L0096:	ldy     #$05
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	jmp     L0094
;
; fwx_start();
;
L0095:	jsr     _fwx_start
;
; fwx_write_u8(FWX_CMD_SD_FILE_COUNT);
;
	lda     #$0B
	jsr     _fwx_write_u8
;
; file_count = fwx_read_u8();
;
	jsr     _fwx_read_u8
	ldx     #$00
	sta     L0074
	stx     L0074+1
;
; for (i = 0; i < file_count && i < 30; ++i) {
;
	ldy     #$05
	txa
	sta     (sp),y
	iny
	sta     (sp),y
L00AF:	ldy     #$06
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	cmp     L0074
	txa
	sbc     L0074+1
	bvc     L0113
	eor     #$80
L0113:	jpl     L00B0
	iny
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	cmp     #$1E
	txa
	sbc     #$00
	bvc     L00B7
	eor     #$80
L00B7:	jpl     L00B0
;
; fwx_write_u8(FWX_CMD_SD_IS_DIR_IDX);
;
	lda     #$08
	jsr     _fwx_write_u8
;
; fwx_write_u8(i & 0xff);
;
	ldy     #$05
	lda     (sp),y
	jsr     _fwx_write_u8
;
; is_dir = fwx_read_u8();
;
	jsr     _fwx_read_u8
	ldy     #$00
	sta     (sp),y
;
; fwx_write_u8(FWX_CMD_SD_FILENAME_IDX);
;
	lda     #$04
	jsr     _fwx_write_u8
;
; fwx_write_u8(i & 0xff);
;
	ldy     #$05
	lda     (sp),y
	jsr     _fwx_write_u8
;
; itoa(i + 1, idx_str, 10);
;
	jsr     decsp4
	ldy     #$0A
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$01
	bcc     L00C6
	inx
L00C6:	ldy     #$02
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     #<(L0078)
	ldy     #$00
	sta     (sp),y
	iny
	lda     #>(L0078)
	sta     (sp),y
	ldx     #$00
	lda     #$0A
	jsr     _itoa
;
; vram_write_cstr(0, i, idx_str);
;
	jsr     decsp4
	lda     #$00
	ldy     #$02
	sta     (sp),y
	iny
	sta     (sp),y
	ldy     #$0A
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$00
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     #<(L0078)
	ldx     #>(L0078)
	jsr     _vram_write_cstr
;
; vram_write_cstr(2, i, " ");
;
	jsr     decsp4
	lda     #$02
	tay
	sta     (sp),y
	iny
	lda     #$00
	sta     (sp),y
	ldy     #$0A
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$00
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     #<(L00D0)
	ldx     #>(L00D0)
	jsr     _vram_write_cstr
;
; for (j = 0; FWXSTAT & FWX_STAT_S1; ++j) {
;
	ldy     #$03
	lda     #$00
	sta     (sp),y
	iny
	sta     (sp),y
L00D2:	lda     $4018
	and     #$20
	beq     L00D3
;
; filename[j] = (char) fwx_read_u8();
;
	lda     #<(L0076)
	ldy     #$03
	clc
	adc     (sp),y
	pha
	lda     #>(L0076)
	iny
	adc     (sp),y
	tax
	pla
	jsr     pushax
	jsr     _fwx_read_u8
	ldy     #$00
	jsr     staspidx
;
; for (j = 0; FWXSTAT & FWX_STAT_S1; ++j) {
;
	ldy     #$03
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	jmp     L00D2
;
; filename_len = strlen(filename);
;
L00D3:	lda     #<(L0076)
	ldx     #>(L0076)
	jsr     _strlen
	ldy     #$01
	jsr     staxysp
;
; for (j = 0; j < filename_len + 1; ++j) {
;
	ldy     #$03
	lda     #$00
	sta     (sp),y
	iny
	sta     (sp),y
L00E1:	ldy     #$06
	jsr     pushwysp
	ldy     #$04
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$01
	bcc     L00E8
	inx
L00E8:	jsr     tosicmp
	jcs     L00B1
;
; char ch = filename[j];
;
	lda     #<(L0076)
	ldy     #$03
	clc
	adc     (sp),y
	sta     ptr1
	lda     #>(L0076)
	iny
	adc     (sp),y
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	jsr     pusha
;
; if (ch == '\0' || j == 29) {
;
	ldy     #$00
	lda     (sp),y
	beq     L0119
	ldy     #$05
	lda     (sp),y
	bne     L00EC
	dey
	lda     (sp),y
	cmp     #$1D
	bne     L00EC
;
; if (is_dir) {
;
L0119:	ldy     #$01
	lda     (sp),y
	beq     L00F0
;
; vram_write_xy(3 + j, i, '/');
;
	jsr     decsp4
	ldy     #$09
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$03
	bcc     L00F4
	inx
L00F4:	ldy     #$02
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	ldy     #$0B
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$00
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     #$2F
	jsr     _vram_write_xy
;
; break;
;
L00F0:	jsr     incsp1
	jmp     L00B1
;
; vram_write_xy(3 + j, i, ch);
;
L00EC:	jsr     decsp4
	ldy     #$09
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$03
	bcc     L00FA
	inx
L00FA:	ldy     #$02
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	ldy     #$0B
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$00
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	ldy     #$04
	lda     (sp),y
	jsr     _vram_write_xy
;
; }
;
	jsr     incsp1
;
; for (j = 0; j < filename_len + 1; ++j) {
;
	ldy     #$03
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	jmp     L00E1
;
; for (i = 0; i < file_count && i < 30; ++i) {
;
L00B1:	ldy     #$05
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	jmp     L00AF
;
; fwx_write_u8(FWX_CMD_SD_LOAD_IDX);
;
L00B0:	lda     #$03
	jsr     _fwx_write_u8
;
; fwx_write_u8(17);
;
	lda     #$11
	jsr     _fwx_write_u8
;
; fwx_stop();
;
	jsr     _fwx_stop
;
; PPU_SCROLL = 0x00; // horizontal offset
;
	lda     #$00
	sta     $2005
;
; PPU_SCROLL = 0x00; // vertical offset
;
	sta     $2005
;
; PPU_CTRL = 0x80;
;
	lda     #$80
	sta     $2000
;
; PPU_MASK = 0x1e; // show sprites and background in color
;
	lda     #$1E
	sta     $2001
;
; for (;;) {
;
L0110:	jmp     L0110

.endproc

