;
; File generated by cc65 v 2.18 - Git ece63f0
;
	.fopt		compiler,"cc65 v 2.18 - Git ece63f0"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_pal_bg
	.import		_pal_spr
	.import		_ppu_wait_nmi
	.import		_ppu_off
	.import		_ppu_on_all
	.import		_oam_clear
	.import		_oam_spr
	.import		_pad_poll
	.import		_bank_spr
	.import		_vram_adr
	.import		_vram_put
	.import		_vram_fill
	.import		_delay
	.import		_itoa
	.export		_type
	.export		_show_credits
	.export		_main

.segment	"RODATA"

_palette_bg:
	.byte	$0F
	.byte	$30
	.byte	$30
	.byte	$30
	.byte	$0F
	.byte	$30
	.byte	$30
	.byte	$28
	.byte	$0F
	.byte	$30
	.byte	$30
	.byte	$30
	.byte	$0F
	.byte	$30
	.byte	$30
	.byte	$30
_palette_credits:
	.byte	$0F
	.byte	$11
	.byte	$28
	.byte	$21
	.byte	$0F
	.byte	$30
	.byte	$30
	.byte	$30
	.byte	$0F
	.byte	$30
	.byte	$30
	.byte	$30
	.byte	$0F
	.byte	$30
	.byte	$30
	.byte	$30
L004B:
	.byte	$42,$49,$4F,$53,$20,$76,$31,$2E,$30,$20,$20,$20,$20,$20,$20,$20
	.byte	$20,$20,$28,$43,$29,$20,$41,$2E,$20,$4B,$61,$63,$68,$61,$65,$76
	.byte	$00
L0050:
	.byte	$45,$6D,$75,$20,$46,$57,$20,$76,$31,$2E,$30,$20,$20,$20,$20,$20
	.byte	$20,$20,$20,$20,$20,$20,$4A,$2E,$20,$4A,$61,$6E,$73,$61,$00
L01FF:
	.byte	$67,$69,$74,$68,$75,$62,$2E,$63,$6F,$6D,$2F,$69,$6E,$75,$6E,$69
	.byte	$78,$33,$2F,$66,$77,$6B,$65,$73,$00
L01EB:
	.byte	$4F,$6E,$20,$70,$72,$6F,$6A,$65,$63,$74,$20,$77,$6F,$72,$6B,$65
	.byte	$64,$3A,$00
L01F0	:=	L004B+22
L01FA:
	.byte	$53,$4F,$43,$20,$32,$30,$32,$36,$00
L01F5	:=	L0050+22
L0142:
	.byte	$4C,$4F,$41,$44,$49,$4E,$47,$00

.segment	"BSS"

_filename:
	.res	30,$00
_filename_len:
	.res	1,$00
_cursor:
	.res	2,$00
_old_cursor:
	.res	2,$00
_page:
	.res	1,$00
_old_page:
	.res	1,$00
_file_count:
	.res	1,$00
_i:
	.res	2,$00
_j:
	.res	2,$00
_is_dir:
	.res	1,$00
_pad1:
	.res	1,$00
_pad1_last:
	.res	1,$00
_pad1_pressed:
	.res	1,$00
_y:
	.res	1,$00
_type:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ print_at (unsigned int, unsigned int, __near__ const unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_print_at: near

.segment	"CODE"

;
; static void print_at(unsigned x, unsigned y, const char *text) {
;
	jsr     pushax
;
; vram_adr(NTADR_A(x, y));
;
	ldy     #$03
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldy     #$05
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ora     ptr1
	pha
	txa
	ora     tmp1
	tax
	pla
	pha
	txa
	ora     #$20
	tax
	pla
	jsr     _vram_adr
;
; while (*text) {
;
	jmp     L0042
;
; vram_put((unsigned char) *text);
;
L0040:	ldy     #$01
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	lda     (ptr1),y
	jsr     _vram_put
;
; ++text;
;
	ldx     #$00
	lda     #$01
	jsr     addeq0sp
;
; while (*text) {
;
L0042:	ldy     #$01
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	lda     (ptr1),y
	bne     L0040
;
; }
;
	jmp     incsp6

.endproc

; ---------------------------------------------------------------
; void __near__ draw_header (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_header: near

.segment	"CODE"

;
; print_at(0, 0, "BIOS v1.0         (C) A. Kachaev");
;
	jsr     decsp4
	lda     #$00
	ldy     #$02
	sta     (sp),y
	iny
	sta     (sp),y
	tay
	sta     (sp),y
	iny
	sta     (sp),y
	lda     #<(L004B)
	ldx     #>(L004B)
	jsr     _print_at
;
; print_at(0, 1, "Emu FW v1.0           J. Jansa");
;
	jsr     decsp4
	lda     #$00
	ldy     #$02
	sta     (sp),y
	iny
	sta     (sp),y
	lda     #$01
	ldy     #$00
	sta     (sp),y
	iny
	lda     #$00
	sta     (sp),y
	lda     #<(L0050)
	ldx     #>(L0050)
	jmp     _print_at

.endproc

; ---------------------------------------------------------------
; void __near__ fetch_filename (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_fetch_filename: near

.segment	"CODE"

;
; static void fetch_filename(uint8_t idx) {
;
	jsr     pusha
;
; fwx_write_u8(FWX_CMD_SD_GET_ENTRY);
;
	lda     #$0B
	sta     $401A
	lda     $4019
	ora     #$02
	sta     $4019
;
; fwx_write_u8(idx);
;
	ldy     #$00
	lda     (sp),y
	sta     $401A
	lda     $4019
	ora     #$02
	sta     $4019
;
; type = fwx_read_u8();
;
	ora     #$02
	sta     $4019
	lda     $401A
	sta     _type
;
; is_dir = (type > 0);
;
	lda     _type
	jsr     boolne
	sta     _is_dir
;
; filename_len = 0;
;
	stx     _filename_len
;
; while (FWXSTAT & FWX_STAT_S1) {
;
	jmp     L023C
;
; char c = (char)fwx_read_u8();
;
L023A:	lda     $4019
	ora     #$02
	sta     $4019
	lda     $401A
	jsr     pusha
;
; if (c == 0) break;
;
	ldy     #$00
	lda     (sp),y
	bne     L023B
	jsr     incsp1
	jmp     L006E
;
; if (filename_len < 29) {
;
L023B:	lda     _filename_len
	cmp     #$1D
	bcs     L007A
;
; filename[filename_len++] = c;
;
	inc     _filename_len
	clc
	adc     #<(_filename)
	sta     ptr1
	tya
	adc     #>(_filename)
	sta     ptr1+1
	lda     (sp),y
	sta     (ptr1),y
;
; }
;
L007A:	jsr     incsp1
;
; while (FWXSTAT & FWX_STAT_S1) {
;
L023C:	lda     $4018
	and     #$20
	bne     L023A
;
; if (is_dir && filename_len < 29) {
;
L006E:	lda     _is_dir
	beq     L007F
	lda     _filename_len
	cmp     #$1D
	bcs     L007F
;
; filename[filename_len++] = '/';
;
	inc     _filename_len
	clc
	adc     #<(_filename)
	sta     ptr1
	tya
	adc     #>(_filename)
	sta     ptr1+1
	lda     #$2F
	sta     (ptr1),y
;
; filename[filename_len] = '\0';
;
L007F:	ldy     _filename_len
	lda     #$00
	sta     _filename,y
;
; }
;
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ clear_screen (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_clear_screen: near

.segment	"CODE"

;
; vram_adr(NAMETABLE);
;
	ldx     #$20
	lda     #$00
	jsr     _vram_adr
;
; vram_fill(' ', 960);
;
	lda     #$20
	jsr     pusha
	ldx     #$03
	lda     #$C0
	jsr     _vram_fill
;
; vram_adr(ATTABLE);
;
	ldx     #$23
	lda     #$C0
	jsr     _vram_adr
;
; vram_fill(0x00, 64);
;
	lda     #$00
	jsr     pusha
	tax
	lda     #$40
	jmp     _vram_fill

.endproc

; ---------------------------------------------------------------
; void __near__ clear_page_area (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_clear_page_area: near

.segment	"CODE"

;
; vram_adr(NAMETABLE);
;
	ldx     #$20
	lda     #$00
	jsr     _vram_adr
;
; for (i = PAGE_Y; i < 30; ++i) {
;
	ldx     #$00
	lda     #$03
	sta     _i
	stx     _i+1
L0099:	lda     _i+1
	cmp     #$00
	bne     L00A0
	lda     _i
	cmp     #$1E
L00A0:	bcs     L009A
;
; vram_adr(NTADR_A(0, i));
;
	lda     _i
	ldx     _i+1
	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _vram_adr
;
; vram_fill(' ', 32);
;
	lda     #$20
	jsr     pusha
	ldx     #$00
	jsr     _vram_fill
;
; for (i = PAGE_Y; i < 30; ++i) {
;
	inc     _i
	bne     L0099
	inc     _i+1
	jmp     L0099
;
; }
;
L009A:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ draw_filename (unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_filename: near

.segment	"BSS"

L00AF:
	.res	4,$00

.segment	"CODE"

;
; static void draw_filename(uint8_t idx, bool loaded) {
;
	jsr     pusha
;
; y = PAGE_Y + idx % FILES_PER_PAGE;
;
	ldy     #$01
	lda     (sp),y
	jsr     pusha0
	lda     #$1A
	jsr     tosumoda0
	clc
	adc     #$03
	sta     _y
;
; itoa(idx + 1, idx_str, 10);
;
	jsr     decsp4
	ldy     #$05
	ldx     #$00
	lda     (sp),y
	clc
	adc     #$01
	bcc     L00B5
	inx
L00B5:	ldy     #$02
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     #<(L00AF)
	ldy     #$00
	sta     (sp),y
	iny
	lda     #>(L00AF)
	sta     (sp),y
	ldx     #$00
	lda     #$0A
	jsr     _itoa
;
; idx_str[3] = 0;
;
	lda     #$00
	sta     L00AF+3
;
; print_at(0, y, idx_str);
;
	jsr     decsp4
	lda     #$00
	ldy     #$02
	sta     (sp),y
	iny
	sta     (sp),y
	lda     _y
	ldy     #$00
	sta     (sp),y
	iny
	lda     #$00
	sta     (sp),y
	lda     #<(L00AF)
	ldx     #>(L00AF)
	jsr     _print_at
;
; vram_adr(NTADR_A(4, y));
;
	ldx     #$00
	lda     _y
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	ora     #$04
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _vram_adr
;
; for (j = 0; filename[j]; ++j) {
;
	lda     #$00
	sta     _j
	sta     _j+1
L00C6:	lda     #<(_filename)
	sta     ptr1
	lda     #>(_filename)
	clc
	adc     _j+1
	sta     ptr1+1
	ldy     _j
	lda     (ptr1),y
	beq     L00C7
;
; uint8_t ch = (uint8_t) filename[j];
;
	lda     #<(_filename)
	sta     ptr1
	lda     #>(_filename)
	clc
	adc     _j+1
	sta     ptr1+1
	ldy     _j
	lda     (ptr1),y
	jsr     pusha
;
; vram_put(loaded ? ch + 0x70 : ch);
;
	ldy     #$01
	lda     (sp),y
	beq     L00D4
	dey
	lda     (sp),y
	clc
	adc     #$70
	jmp     L0240
L00D4:	dey
	lda     (sp),y
L0240:	jsr     _vram_put
;
; }
;
	jsr     incsp1
;
; for (j = 0; filename[j]; ++j) {
;
	inc     _j
	bne     L00C6
	inc     _j+1
	jmp     L00C6
;
; }
;
L00C7:	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ draw_page (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_page: near

.segment	"CODE"

;
; unsigned idx = 0;
;
	jsr     push0
;
; for (i = 0; i < FILES_PER_PAGE; ++i) {
;
	sta     _i
	sta     _i+1
L00DB:	lda     _i+1
	cmp     #$00
	bne     L00E2
	lda     _i
	cmp     #$1A
L00E2:	bcs     L00DC
;
; idx = page * FILES_PER_PAGE + i;
;
	lda     _page
	jsr     pusha0
	lda     #$1A
	jsr     tosumula0
	clc
	adc     _i
	pha
	txa
	adc     _i+1
	tax
	pla
	jsr     stax0sp
;
; if (idx >= file_count) {
;
	cmp     _file_count
	txa
	sbc     #$00
;
; break;
;
	bcs     L00DC
;
; fetch_filename(idx);
;
	ldy     #$00
	lda     (sp),y
	jsr     _fetch_filename
;
; draw_filename(idx, false);
;
	ldy     #$00
	lda     (sp),y
	jsr     pusha
	lda     #$00
	jsr     _draw_filename
;
; for (i = 0; i < FILES_PER_PAGE; ++i) {
;
	inc     _i
	bne     L00DB
	inc     _i+1
	jmp     L00DB
;
; }
;
L00DC:	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ draw_cursor (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_cursor: near

.segment	"CODE"

;
; oam_clear();
;
	jsr     _oam_clear
;
; y = PAGE_Y + cursor % FILES_PER_PAGE;
;
	lda     _cursor
	ldx     _cursor+1
	jsr     pushax
	ldx     #$00
	lda     #$1A
	jsr     tosmoda0
	clc
	adc     #$03
	sta     _y
;
; oam_spr(24, y * 8, 0x80, 0x01);
;
	jsr     decsp3
	lda     #$18
	ldy     #$02
	sta     (sp),y
	lda     _y
	asl     a
	asl     a
	asl     a
	dey
	sta     (sp),y
	lda     #$80
	dey
	sta     (sp),y
	lda     #$01
	jmp     _oam_spr

.endproc

; ---------------------------------------------------------------
; void __near__ init (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_init: near

.segment	"CODE"

;
; ppu_off();
;
	jsr     _ppu_off
;
; pal_bg(palette_bg);
;
	lda     #<(_palette_bg)
	ldx     #>(_palette_bg)
	jsr     _pal_bg
;
; pal_spr(palette_bg);
;
	lda     #<(_palette_bg)
	ldx     #>(_palette_bg)
	jsr     _pal_spr
;
; bank_spr(0);
;
	lda     #$00
	jsr     _bank_spr
;
; clear_screen();
;
	jsr     _clear_screen
;
; draw_header();
;
	jsr     _draw_header
;
; fwx_start();
;
	lda     #$01
	sta     $4019
;
; fwx_write_u8(FWX_CMD_SD_FILE_COUNT);
;
	lda     #$08
	sta     $401A
	lda     $4019
	ora     #$02
	sta     $4019
;
; file_count = fwx_read_u8();
;
	ora     #$02
	sta     $4019
	lda     $401A
	sta     _file_count
;
; draw_page();
;
	jsr     _draw_page
;
; draw_cursor();
;
	jsr     _draw_cursor
;
; ppu_on_all();
;
	jmp     _ppu_on_all

.endproc

; ---------------------------------------------------------------
; void __near__ read_input (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_read_input: near

.segment	"CODE"

;
; pad1_last = pad1;
;
	lda     _pad1
	sta     _pad1_last
;
; pad1 = pad_poll(0);
;
	lda     #$00
	jsr     _pad_poll
	sta     _pad1
;
; pad1_pressed = pad1 & ~pad1_last;
;
	lda     _pad1_last
	eor     #$FF
	and     _pad1
	sta     _pad1_pressed
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ wrap_cursor (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_wrap_cursor: near

.segment	"CODE"

;
; if (cursor < 0) {
;
	ldx     _cursor+1
	cpx     #$80
	bcc     L0120
;
; cursor = file_count - 1;
;
	ldx     #$00
	lda     _file_count
	sec
	sbc     #$01
	bcs     L0242
	dex
;
; } else if (cursor >= file_count) {
;
	jmp     L0242
L0120:	lda     _cursor
	cmp     _file_count
	lda     _cursor+1
	sbc     #$00
	bcc     L0126
;
; cursor = 0;
;
	ldx     #$00
	txa
L0242:	sta     _cursor
	stx     _cursor+1
;
; }
;
L0126:	rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ cursor_within_page (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_cursor_within_page: near

.segment	"CODE"

;
; return cursor / FILES_PER_PAGE;
;
	lda     _cursor
	ldx     _cursor+1
	jsr     pushax
	lda     #$1A
	jsr     tosdiva0
	ldx     #$00
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ move_cursor (int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_move_cursor: near

.segment	"CODE"

;
; static void move_cursor(int delta) {
;
	jsr     pushax
;
; old_cursor = cursor;
;
	lda     _cursor+1
	sta     _old_cursor+1
	lda     _cursor
	sta     _old_cursor
;
; old_page = page;
;
	lda     _page
	sta     _old_page
;
; cursor += delta;
;
	ldy     #$01
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     _cursor
	sta     _cursor
	txa
	adc     _cursor+1
	sta     _cursor+1
;
; wrap_cursor();
;
	jsr     _wrap_cursor
;
; page = cursor_within_page();
;
	jsr     _cursor_within_page
	sta     _page
;
; if (page != old_page) {
;
	lda     _old_page
	cmp     _page
	beq     L0136
;
; ppu_off();
;
	jsr     _ppu_off
;
; clear_page_area();
;
	jsr     _clear_page_area
;
; draw_page();
;
	jsr     _draw_page
;
; ppu_on_all();
;
	jsr     _ppu_on_all
;
; draw_cursor();
;
L0136:	jsr     _draw_cursor
;
; }
;
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ draw_loading (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_loading: near

.segment	"CODE"

;
; clear_screen();
;
	jsr     _clear_screen
;
; print_at(11, 14, "LOADING");
;
	jsr     decsp4
	lda     #$0B
	ldy     #$02
	sta     (sp),y
	iny
	lda     #$00
	sta     (sp),y
	lda     #$0E
	ldy     #$00
	sta     (sp),y
	iny
	lda     #$00
	sta     (sp),y
	lda     #<(L0142)
	ldx     #>(L0142)
	jmp     _print_at

.endproc

; ---------------------------------------------------------------
; void __near__ load_rom (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_load_rom: near

.segment	"CODE"

;
; ppu_off();
;
	jsr     _ppu_off
;
; oam_clear();
;
	jsr     _oam_clear
;
; draw_loading();
;
	jsr     _draw_loading
;
; ppu_on_all();
;
	jsr     _ppu_on_all
;
; delay(5);
;
	lda     #$05
	jsr     _delay
;
; fwx_write_u8(FWX_CMD_SD_LOAD);
;
	lda     #$03
	sta     $401A
	lda     $4019
	ora     #$02
	sta     $4019
;
; fwx_write_u8(cursor & 0xff);
;
	lda     _cursor
	sta     $401A
	lda     $4019
	ora     #$02
	sta     $4019
;
; if (fwx_last_error() != FWX_ERR_OK) {
;
	lda     $4018
	and     #$0F
	beq     L0159
;
; fwx_write_u8(FWX_CMD_LED_ERROR);
;
	lda     #$09
	sta     $401A
	lda     $4019
	ora     #$02
	sta     $4019
;
; fwx_write_u8(1);
;
	lda     #$01
	sta     $401A
	lda     $4019
	ora     #$02
	sta     $4019
;
; ppu_off();
;
	jsr     _ppu_off
;
; clear_screen();
;
	jsr     _clear_screen
;
; draw_header();
;
	jsr     _draw_header
;
; draw_page();
;
	jsr     _draw_page
;
; draw_cursor();
;
	jsr     _draw_cursor
;
; ppu_on_all();
;
	jmp     _ppu_on_all
;
; ppu_off();
;
L0159:	jsr     _ppu_off
;
; fwx_write_u8(FWX_CMD_SD_FILE_COUNT);
;
	lda     #$08
	sta     $401A
	lda     $4019
	ora     #$02
	sta     $4019
;
; file_count = fwx_read_u8();
;
	ora     #$02
	sta     $4019
	lda     $401A
	sta     _file_count
;
; old_cursor = 0;
;
	lda     #$00
	sta     _old_cursor
	sta     _old_cursor+1
;
; cursor = 0;
;
	sta     _cursor
	sta     _cursor+1
;
; page = 0;
;
	sta     _page
;
; old_page = 0;
;
	sta     _old_page
;
; clear_screen();
;
	jsr     _clear_screen
;
; draw_header();
;
	jsr     _draw_header
;
; draw_page();
;
	jsr     _draw_page
;
; draw_cursor();
;
	jsr     _draw_cursor
;
; ppu_on_all();
;
	jmp     _ppu_on_all

.endproc

; ---------------------------------------------------------------
; void __near__ show_credits (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_show_credits: near

.segment	"CODE"

;
; ppu_off();
;
	jsr     _ppu_off
;
; oam_clear();
;
	jsr     _oam_clear
;
; clear_screen();
;
	jsr     _clear_screen
;
; pal_bg(palette_credits);
;
	lda     #<(_palette_credits)
	ldx     #>(_palette_credits)
	jsr     _pal_bg
;
; vram_adr(NTADR_A(1, 4));  vram_fill('-', 30);
;
	ldx     #$20
	lda     #$81
	jsr     _vram_adr
	lda     #$2D
	jsr     pusha
	ldx     #$00
	lda     #$1E
	jsr     _vram_fill
;
; vram_adr(NTADR_A(1, 24)); vram_fill('-', 30);
;
	ldx     #$23
	lda     #$01
	jsr     _vram_adr
	lda     #$2D
	jsr     pusha
	ldx     #$00
	lda     #$1E
	jsr     _vram_fill
;
; for(i = 5; i < 24; ++i) {
;
	ldx     #$00
	lda     #$05
	sta     _i
	stx     _i+1
L01A8:	lda     _i+1
	cmp     #$00
	bne     L01AF
	lda     _i
	cmp     #$18
L01AF:	bcs     L01A9
;
; vram_adr(NTADR_A(1, i));  vram_put('|');
;
	lda     _i
	ldx     _i+1
	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	ora     #$01
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _vram_adr
	lda     #$7C
	jsr     _vram_put
;
; vram_adr(NTADR_A(30, i)); vram_put('|');
;
	lda     _i
	ldx     _i+1
	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	ora     #$1E
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _vram_adr
	lda     #$7C
	jsr     _vram_put
;
; for(i = 5; i < 24; ++i) {
;
	inc     _i
	bne     L01A8
	inc     _i+1
	jmp     L01A8
;
; vram_adr(NTADR_A(1, 4));   vram_put('+');
;
L01A9:	ldx     #$20
	lda     #$81
	jsr     _vram_adr
	lda     #$2B
	jsr     _vram_put
;
; vram_adr(NTADR_A(30, 4));  vram_put('+');
;
	ldx     #$20
	lda     #$9E
	jsr     _vram_adr
	lda     #$2B
	jsr     _vram_put
;
; vram_adr(NTADR_A(1, 24));  vram_put('+');
;
	ldx     #$23
	lda     #$01
	jsr     _vram_adr
	lda     #$2B
	jsr     _vram_put
;
; vram_adr(NTADR_A(30, 24)); vram_put('+');
;
	ldx     #$23
	lda     #$1E
	jsr     _vram_adr
	lda     #$2B
	jsr     _vram_put
;
; print_at(7, 8, "On project worked:");
;
	jsr     decsp4
	lda     #$07
	ldy     #$02
	sta     (sp),y
	iny
	lda     #$00
	sta     (sp),y
	lda     #$08
	ldy     #$00
	sta     (sp),y
	iny
	lda     #$00
	sta     (sp),y
	lda     #<(L01EB)
	ldx     #>(L01EB)
	jsr     _print_at
;
; print_at(11, 11, "A. Kachaev");
;
	jsr     decsp4
	lda     #$0B
	ldy     #$02
	sta     (sp),y
	iny
	lda     #$00
	sta     (sp),y
	lda     #$0B
	ldy     #$00
	sta     (sp),y
	iny
	lda     #$00
	sta     (sp),y
	lda     #<(L01F0)
	ldx     #>(L01F0)
	jsr     _print_at
;
; print_at(12, 12, "J. Jansa");
;
	jsr     decsp4
	lda     #$0C
	ldy     #$02
	sta     (sp),y
	iny
	lda     #$00
	sta     (sp),y
	lda     #$0C
	ldy     #$00
	sta     (sp),y
	iny
	lda     #$00
	sta     (sp),y
	lda     #<(L01F5)
	ldx     #>(L01F5)
	jsr     _print_at
;
; print_at(12, 17, "SOC 2026");
;
	jsr     decsp4
	lda     #$0C
	ldy     #$02
	sta     (sp),y
	iny
	lda     #$00
	sta     (sp),y
	lda     #$11
	ldy     #$00
	sta     (sp),y
	iny
	lda     #$00
	sta     (sp),y
	lda     #<(L01FA)
	ldx     #>(L01FA)
	jsr     _print_at
;
; print_at(4, 21, "github.com/inunix3/fwkes");
;
	jsr     decsp4
	lda     #$04
	ldy     #$02
	sta     (sp),y
	iny
	lda     #$00
	sta     (sp),y
	lda     #$15
	ldy     #$00
	sta     (sp),y
	iny
	lda     #$00
	sta     (sp),y
	lda     #<(L01FF)
	ldx     #>(L01FF)
	jsr     _print_at
;
; ppu_wait_nmi();
;
	jsr     _ppu_wait_nmi
;
; ppu_on_all();
;
	jsr     _ppu_on_all
;
; while(pad_poll(0) != 0);
;
L0203:	lda     #$00
	jsr     _pad_poll
	cmp     #$00
	bne     L0203
;
; while(pad_poll(0) == 0);
;
L0244:	jsr     _pad_poll
	cmp     #$00
	beq     L0244
;
; ppu_off();
;
	jsr     _ppu_off
;
; pal_bg(palette_bg);
;
	lda     #<(_palette_bg)
	ldx     #>(_palette_bg)
	jsr     _pal_bg
;
; clear_screen();
;
	jsr     _clear_screen
;
; draw_header();
;
	jsr     _draw_header
;
; draw_page();
;
	jsr     _draw_page
;
; draw_cursor();
;
	jsr     _draw_cursor
;
; ppu_on_all();
;
	jmp     _ppu_on_all

.endproc

; ---------------------------------------------------------------
; void __near__ handle_input (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_handle_input: near

.segment	"CODE"

;
; if (pad1_pressed & PAD_DOWN) {
;
	lda     _pad1_pressed
	and     #$04
	beq     L0245
;
; move_cursor(+1);
;
	ldx     #$00
	lda     #$01
	jmp     _move_cursor
;
; } else if (pad1_pressed & PAD_UP) {
;
L0245:	lda     _pad1_pressed
	and     #$08
	beq     L0246
;
; move_cursor(-1);
;
	ldx     #$FF
	txa
	jmp     _move_cursor
;
; } else if (pad1_pressed & PAD_LEFT) {
;
L0246:	lda     _pad1_pressed
	and     #$02
	beq     L0247
;
; move_cursor(-FILES_PER_PAGE);
;
	ldx     #$FF
	lda     #$E6
	jmp     _move_cursor
;
; } else if (pad1_pressed & PAD_RIGHT) {
;
L0247:	lda     _pad1_pressed
	and     #$01
	beq     L0248
;
; move_cursor(+FILES_PER_PAGE);
;
	ldx     #$00
	lda     #$1A
	jmp     _move_cursor
;
; } else if (pad1_pressed & PAD_START) {
;
L0248:	lda     _pad1_pressed
	and     #$10
	cmp     #$00
;
; load_rom();
;
	jne     _load_rom
;
; } else if(pad1_pressed & PAD_A){
;
	lda     _pad1_pressed
	and     #$80
	cmp     #$00
;
; show_credits();
;
	jne     _show_credits
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

;
; init();
;
	jsr     _init
;
; ppu_wait_nmi();
;
L0236:	jsr     _ppu_wait_nmi
;
; read_input();
;
	jsr     _read_input
;
; handle_input();
;
	jsr     _handle_input
;
; }
;
	jmp     L0236

.endproc

