@startuml
skinparam defaultFontName Linux Biolinum G
scale 1 as 75 pixels

clock "Hodiny" as clk with period 1
rectangle "Fáze" as F

@0
F is Fetch

@1
F is Decode

@2
F is Execute

@3
F is Write

@4
F is Fetch...

@0 <-> @4 : Instrukční cyklus

@enduml
