@startuml
skinparam defaultFontName Linux Biolinum G
scale 1 as 75 pixels

binary "CLK" as CLK
concise "DATA" as DATA
binary "S1" as S1

@1 as :data_0_beg
@3 as :data_0_end
@4 as :data_n_beg
@6 as :data_n_end

CLK is low
S1 is low

@0
S1 is high

@1
CLK is high
DATA is "data[0]"
S1 is high

@2
CLK is low

@3
CLK is {low,high}
DATA is "..."

@4
CLK is high
DATA is "data[n]"

@5
CLK is low

@6
DATA is {hidden}
S1 is low

highlight :data_0_beg to :data_0_end #Gold:1. byte
highlight :data_0_end to :data_n_beg #Yellow
highlight :data_n_beg to :data_n_end #Gold:n-tý byte

@enduml
