@startuml
skinparam defaultFontName Linux Biolinum G
scale 1 as 75 pixels
'skinparam dpi 600

binary "SS" as SS
binary "CLK" as CLK
concise "DATA" as DATA
binary "S0" as S0
concise "ER0..ER3" as ER

@1 as :start_beg
@2 as :start_end
@2 as :write_beg
@3 as :write_end
@4 as :stop_beg
@5 as :stop_end

@0
SS is low
CLK is low
S0 is low

@1
SS is high
S0 is high
ER is "0x00"

@2
DATA is "..."
CLK is {low,high}

@3
CLK is low
DATA is {hidden}
ER is {hidden}

@4
SS is low
CLK is low
S0 is low
ER is "výsledný kód"

highlight :start_beg to :start_end #lightBlue:Start
highlight :write_beg to :write_end #Gold:Transakce
highlight :write_end to :stop_beg #lightGreen:Vykonání
highlight :stop_beg to :stop_end #lightBlue:Stop

@3 <-> @4 : emulace je pozastavená

@enduml
