#pragma once

#include "joypad.h"
#include "joyplayer.h"

static const JoyEvent g_demo_events[] = {

    // START DELAY
    {JOY_EVENT_INPUT, 0, 380}, // [0]

    // DOWN x5 (30)
    {JOY_EVENT_INPUT, BTN_DOWN, 10}, // [1]
    {JOY_EVENT_INPUT, 0, 30},         // [2]
    {JOY_EVENT_INPUT, BTN_DOWN, 10}, // [3]
    {JOY_EVENT_INPUT, 0, 30},         // [4]
    {JOY_EVENT_INPUT, BTN_DOWN, 10}, // [5]
    {JOY_EVENT_INPUT, 0, 30},         // [6]
    {JOY_EVENT_INPUT, BTN_DOWN, 10}, // [7]
    {JOY_EVENT_INPUT, 0, 30},         // [8]
    {JOY_EVENT_INPUT, BTN_DOWN, 10}, // [9]
    {JOY_EVENT_INPUT, 0, 30},         // [10]

    // START
    {JOY_EVENT_INPUT, BTN_START, 10}, // [11]
    {JOY_EVENT_INPUT, 0, 30},          // [12]

    // DOWN
    {JOY_EVENT_INPUT, BTN_DOWN, 10},  // [13]
    {JOY_EVENT_INPUT, 0, 30},          // [14]

    // START
    {JOY_EVENT_INPUT, BTN_START, 10}, // [15]
    {JOY_EVENT_INPUT, 0, 30},          // [16]

    // B
    {JOY_EVENT_INPUT, BTN_B, 10},     // [17]
    {JOY_EVENT_INPUT, 0, 30},          // [18]

    {JOY_EVENT_INPUT, BTN_DOWN, 10},  // [19]
    {JOY_EVENT_INPUT, 0, 30},          // [20]

    // A x3 (30)
    {JOY_EVENT_INPUT, BTN_A, 10},     // [21]
    {JOY_EVENT_INPUT, 0, 30},          // [22]
    {JOY_EVENT_INPUT, BTN_A, 10},     // [23]
    {JOY_EVENT_INPUT, 0, 30},          // [24]
    {JOY_EVENT_INPUT, BTN_A, 10},     // [25]
    {JOY_EVENT_INPUT, 0, 30},          // [26]

    {JOY_EVENT_INPUT, BTN_B, 10},     // [27]
    {JOY_EVENT_INPUT, 0, 30},          // [28]

    {JOY_EVENT_INPUT, BTN_DOWN, 10},  // [29]
    {JOY_EVENT_INPUT, 0, 30},          // [30]

    // A x3 (30)
    {JOY_EVENT_INPUT, BTN_A, 10},     // [31]
    {JOY_EVENT_INPUT, 0, 30},          // [32]
    {JOY_EVENT_INPUT, BTN_A, 10},     // [33]
    {JOY_EVENT_INPUT, 0, 30},          // [34]
    {JOY_EVENT_INPUT, BTN_A, 10},     // [35]
    {JOY_EVENT_INPUT, 0, 30},          // [36]

    {JOY_EVENT_INPUT, BTN_B, 10},     // [37]
    {JOY_EVENT_INPUT, 0, 30},          // [38]

    // DOWN x2 (10)
    {JOY_EVENT_INPUT, BTN_DOWN, 10},  // [39]
    {JOY_EVENT_INPUT, 0, 10},          // [40]
    {JOY_EVENT_INPUT, BTN_DOWN, 10},  // [41]
    {JOY_EVENT_INPUT, 0, 10},          // [42]

    // A x4 (20)
    {JOY_EVENT_INPUT, BTN_A, 10},     // [43]
    {JOY_EVENT_INPUT, 0, 20},          // [44]
    {JOY_EVENT_INPUT, BTN_A, 10},     // [45]
    {JOY_EVENT_INPUT, 0, 20},          // [46]
    {JOY_EVENT_INPUT, BTN_A, 10},     // [47]
    {JOY_EVENT_INPUT, 0, 20},          // [48]
    {JOY_EVENT_INPUT, BTN_A, 10},     // [49]
    {JOY_EVENT_INPUT, 0, 20},          // [50]
    {JOY_EVENT_INPUT, BTN_A, 10},     // [51]
    {JOY_EVENT_INPUT, 0, 20},          // [52]

    {JOY_EVENT_INPUT, BTN_B, 10},     // [53]
    {JOY_EVENT_INPUT, 0, 30},          // [54]

    {JOY_EVENT_INPUT, BTN_DOWN, 10},  // [55]
    {JOY_EVENT_INPUT, 0, 30},          // [56]

    {JOY_EVENT_INPUT, BTN_A, 10},     // [57]
    {JOY_EVENT_INPUT, 0, 30},          // [58]

    // RIGHT x5 (30)
    {JOY_EVENT_INPUT, BTN_RIGHT, 10}, // [59] monoscope
    {JOY_EVENT_INPUT, 0, 30},          // [60]
    {JOY_EVENT_INPUT, BTN_RIGHT, 10}, // [61]
    {JOY_EVENT_INPUT, 0, 30},          // [62]
    {JOY_EVENT_INPUT, BTN_RIGHT, 10}, // [63]
    {JOY_EVENT_INPUT, 0, 30},          // [64]
    {JOY_EVENT_INPUT, BTN_RIGHT, 10}, // [65]
    {JOY_EVENT_INPUT, 0, 30},          // [66]
    {JOY_EVENT_INPUT, BTN_RIGHT, 10}, // [67]
    {JOY_EVENT_INPUT, 0, 30},          // [68]

    {JOY_EVENT_INPUT, BTN_B, 10},     // [69]
    {JOY_EVENT_INPUT, 0, 30},          // [70]

    // DOWN x2 (20)
    {JOY_EVENT_INPUT, BTN_DOWN, 10},  // [71]
    {JOY_EVENT_INPUT, 0, 20},          // [72]
    {JOY_EVENT_INPUT, BTN_DOWN, 10},  // [73]
    {JOY_EVENT_INPUT, 0, 20},          // [74]

    {JOY_EVENT_INPUT, BTN_A, 10},     // [75]
    {JOY_EVENT_INPUT, 0, 20},          // [76]

    {JOY_EVENT_INPUT, 0, 60},          // [77]

    {JOY_EVENT_INPUT, BTN_B, 10},     // [78]
    {JOY_EVENT_INPUT, 0, 30},          // [79]

    {JOY_EVENT_INPUT, BTN_DOWN, 10},  // [80]
    {JOY_EVENT_INPUT, 0, 30},          // [81]

    // A x2 (10)
    {JOY_EVENT_INPUT, BTN_A, 10},     // [82]
    {JOY_EVENT_INPUT, 0, 10},          // [83]
    {JOY_EVENT_INPUT, BTN_A, 10},     // [84]
    {JOY_EVENT_INPUT, 0, 10},          // [85]

    // RIGHT x2 (20)
    {JOY_EVENT_INPUT, BTN_RIGHT, 10}, // [86]
    {JOY_EVENT_INPUT, 0, 20},          // [87]
    {JOY_EVENT_INPUT, BTN_RIGHT, 10}, // [88]
    {JOY_EVENT_INPUT, 0, 20},          // [89]
    {JOY_EVENT_INPUT, BTN_RIGHT, 10}, // [90]
    {JOY_EVENT_INPUT, 0, 20},          // [91]

    // DOWN x2 (20)
    {JOY_EVENT_INPUT, BTN_DOWN, 10},  // [92]
    {JOY_EVENT_INPUT, 0, 20},          // [93]
    {JOY_EVENT_INPUT, BTN_DOWN, 10},  // [94]
    {JOY_EVENT_INPUT, 0, 20},          // [95]

    {JOY_EVENT_INPUT, BTN_B, 10},     // [96]
    {JOY_EVENT_INPUT, 0, 30},          // [97]

    // DOWN x2 (10)
    {JOY_EVENT_INPUT, BTN_DOWN, 10},  // [98]
    {JOY_EVENT_INPUT, 0, 10},          // [99]
    {JOY_EVENT_INPUT, BTN_DOWN, 10},  // [100]
    {JOY_EVENT_INPUT, 0, 10},          // [101]

    // A x2 (40)
    {JOY_EVENT_INPUT, BTN_A, 10},     // [102]
    {JOY_EVENT_INPUT, 0, 40},          // [103]
    {JOY_EVENT_INPUT, 0, 70},          // [104]

    {JOY_EVENT_INPUT, BTN_A, 10},     // [105]
    {JOY_EVENT_INPUT, 0, 40},          // [106]

    {JOY_EVENT_INPUT, BTN_B, 10},     // [107]
    {JOY_EVENT_INPUT, 0, 30},          // [108]

    // DOWN x3 (30)
    {JOY_EVENT_INPUT, BTN_DOWN, 10},  // [109]
    {JOY_EVENT_INPUT, 0, 30},          // [110]
    {JOY_EVENT_INPUT, BTN_DOWN, 10},  // [111]
    {JOY_EVENT_INPUT, 0, 30},          // [112]
    {JOY_EVENT_INPUT, BTN_DOWN, 10},  // [113]
    {JOY_EVENT_INPUT, 0, 30},          // [114]

    {JOY_EVENT_INPUT, BTN_A, 10},     // [115]
    {JOY_EVENT_INPUT, 0, 70},          // [116]
    {JOY_EVENT_INPUT, 0, 70},          // [117]

    {JOY_EVENT_INPUT, BTN_B, 10},     // [118]
    {JOY_EVENT_INPUT, 0, 30},          // [119]

    {JOY_EVENT_INPUT, BTN_DOWN, 10},  // [120]
    {JOY_EVENT_INPUT, BTN_A, 10},     // [121]
    {JOY_EVENT_INPUT, 0, 350},         // [122]
    {JOY_EVENT_INPUT, BTN_B, 10},      // [123]

    {JOY_EVENT_INPUT, BTN_RIGHT, 10}, // [124]
    {JOY_EVENT_INPUT, 0, 30},          // [125]

    // UP x8 (10)
    {JOY_EVENT_INPUT, BTN_UP, 10},    // [126]
    {JOY_EVENT_INPUT, 0, 10},          // [127]
    {JOY_EVENT_INPUT, BTN_UP, 10},    // [128]
    {JOY_EVENT_INPUT, 0, 10},          // [129]
    {JOY_EVENT_INPUT, BTN_UP, 10},    // [130]
    {JOY_EVENT_INPUT, 0, 10},          // [131]
    {JOY_EVENT_INPUT, BTN_UP, 10},    // [132]
    {JOY_EVENT_INPUT, 0, 10},          // [133]
    {JOY_EVENT_INPUT, BTN_UP, 10},    // [134]
    {JOY_EVENT_INPUT, 0, 10},          // [135]
    {JOY_EVENT_INPUT, BTN_UP, 10},    // [136]
    {JOY_EVENT_INPUT, 0, 10},          // [137]
    {JOY_EVENT_INPUT, BTN_UP, 10},    // [138]
    {JOY_EVENT_INPUT, 0, 10},          // [139]
    {JOY_EVENT_INPUT, BTN_UP, 10},    // [140]
    {JOY_EVENT_INPUT, 0, 10},          // [141] grid scroll

    {JOY_EVENT_INPUT, BTN_A, 10},     // [142]
    {JOY_EVENT_INPUT, 0, 30},          // [143]

    {JOY_EVENT_INPUT, BTN_B, 10},     // [144]
    {JOY_EVENT_INPUT, 0, 30},          // [145]

    {JOY_EVENT_INPUT, BTN_UP, 10},    // [146]
    {JOY_EVENT_INPUT, 0, 30},          // [147]

    {JOY_EVENT_INPUT, BTN_A, 10},     // [148]
    {JOY_EVENT_INPUT, 0, 30},          // [149]
    {JOY_EVENT_INPUT, 0, 40},          // [150]
    {JOY_EVENT_INPUT, BTN_UP, 10},    // [151]
    {JOY_EVENT_INPUT, 0, 10},          // [152]
    {JOY_EVENT_INPUT, BTN_UP, 10},    // [153]
    {JOY_EVENT_INPUT, 0, 10},          // [154]
    {JOY_EVENT_INPUT, BTN_UP, 10},    // [155]
    {JOY_EVENT_INPUT, 0, 10},          // [156]
    {JOY_EVENT_INPUT, BTN_UP, 10},    // [157]
    {JOY_EVENT_INPUT, 0, 10},          // [158]
    {JOY_EVENT_INPUT, BTN_UP, 10},    // [159]
    {JOY_EVENT_INPUT, 0, 10},          // [160]
    {JOY_EVENT_INPUT, BTN_UP, 10},    // [161]
    {JOY_EVENT_INPUT, 0, 10},          // [162]
    {JOY_EVENT_INPUT, BTN_UP, 10},    // [163]
    {JOY_EVENT_INPUT, 0, 10},          // [164]
    {JOY_EVENT_INPUT, BTN_UP, 10},    // [165]
    {JOY_EVENT_INPUT, 0, 10},          // [166]
    {JOY_EVENT_INPUT, BTN_LEFT, 10},  // [167]
    {JOY_EVENT_INPUT, 0, 10},          // [168]

    {JOY_EVENT_INPUT, BTN_B, 10},     // [169]
    {JOY_EVENT_INPUT, 0, 30},          // [170]

    {JOY_EVENT_INPUT, BTN_UP, 10},    // [171]
    {JOY_EVENT_INPUT, 0, 30},          // [172]

    {JOY_EVENT_INPUT, BTN_A, 10},     // [173]
    {JOY_EVENT_INPUT, 0, 30},          // [174]
    {JOY_EVENT_INPUT, 0, 40},          // [175]
    {JOY_EVENT_INPUT, BTN_UP, 10},    // [176]
    {JOY_EVENT_INPUT, 0, 10},          // [177]
    {JOY_EVENT_INPUT, BTN_UP, 10},    // [178]
    {JOY_EVENT_INPUT, 0, 10},          // [179]
    {JOY_EVENT_INPUT, BTN_UP, 10},    // [180]
    {JOY_EVENT_INPUT, 0, 10},          // [181]
    {JOY_EVENT_INPUT, BTN_UP, 10},    // [182]
    {JOY_EVENT_INPUT, 0, 10},          // [183]
    {JOY_EVENT_INPUT, BTN_UP, 10},    // [184]
    {JOY_EVENT_INPUT, 0, 10},          // [185]
    {JOY_EVENT_INPUT, BTN_UP, 10},    // [186]
    {JOY_EVENT_INPUT, 0, 10},          // [187]
    {JOY_EVENT_INPUT, BTN_UP, 10},    // [188]
    {JOY_EVENT_INPUT, 0, 10},          // [189]
    {JOY_EVENT_INPUT, BTN_UP, 10},    // [190]
    {JOY_EVENT_INPUT, 0, 10},          // [191]
    {JOY_EVENT_INPUT, BTN_LEFT, 10},  // [192]
    {JOY_EVENT_INPUT, 0, 10},          // [193]
    {JOY_EVENT_INPUT, 0, 40},          // [194]
    {JOY_EVENT_INPUT, BTN_B, 10},     // [195]
    {JOY_EVENT_INPUT, 0, 30},          // [196]

    {JOY_EVENT_INPUT, BTN_UP, 10},    // [197]
    {JOY_EVENT_INPUT, 0, 30},          // [198]

    // A
    {JOY_EVENT_INPUT, BTN_A, 10},     // [199]
    {JOY_EVENT_INPUT, 0, 30},          // [200]

    // A
    {JOY_EVENT_INPUT, BTN_A, 10},     // [201]
    {JOY_EVENT_INPUT, 0, 10},          // [202]

    // A
    {JOY_EVENT_INPUT, BTN_A, 10},     // [203]
    {JOY_EVENT_INPUT, 0, 50},          // [204]

    // A
    {JOY_EVENT_INPUT, BTN_A, 10},     // [205]
    {JOY_EVENT_INPUT, 0, 30},          // [206]

    // B
    {JOY_EVENT_INPUT, BTN_B, 10},     // [207]
    {JOY_EVENT_INPUT, 0, 30},          // [208]

    // UP
    {JOY_EVENT_INPUT, BTN_UP, 10},    // [209]
    {JOY_EVENT_INPUT, 0, 30},          // [210]

    // A x2 (20)
    {JOY_EVENT_INPUT, BTN_A, 10},     // [211]
    {JOY_EVENT_INPUT, 0, 20},          // [212]
    {JOY_EVENT_INPUT, BTN_A, 10},     // [213]
    {JOY_EVENT_INPUT, 0, 20},          // [214]

    {JOY_EVENT_INPUT, 0, 120},         // [215]

    // B
    {JOY_EVENT_INPUT, BTN_B, 10},     // [216]
    {JOY_EVENT_INPUT, 0, 30},          // [217]

    {JOY_EVENT_INPUT, BTN_UP, 10},    // [218]
    {JOY_EVENT_INPUT, 0, 30},          // [219]

    {JOY_EVENT_INPUT, BTN_A, 10},     // [220]
    {JOY_EVENT_INPUT, 0, 30},          // [221]

    {JOY_EVENT_INPUT, 0, 33},          // [222]
    {JOY_EVENT_INPUT, 0, 120},         // [223]
    {JOY_EVENT_INPUT, BTN_B, 10},     // [224]
    {JOY_EVENT_INPUT, 0, 30},          // [225]

    // --- RESET ---
    {JOY_EVENT_INPUT, 0, 120},         // [226]
    {JOY_EVENT_RESET, 0, 0},           // [227]
    {JOY_EVENT_INPUT, 0, 180},         // [228]

    {JOY_EVENT_INPUT, BTN_START, 10}, // [229]
    {JOY_EVENT_INPUT, 0, 60},          // [230]
    {JOY_EVENT_INPUT, BTN_A, 10},     // [231]
    {JOY_EVENT_INPUT, 0, 300},         // [232]

    {JOY_EVENT_INPUT, BTN_A, 10},     // [233]
    {JOY_EVENT_INPUT, 0, 30},          // [234]

    {JOY_EVENT_INPUT, BTN_DOWN, 10},  // [235]
    {JOY_EVENT_INPUT, 0, 30},          // [236]
    {JOY_EVENT_INPUT, BTN_DOWN, 10},  // [237]
    {JOY_EVENT_INPUT, 0, 30},          // [238]

    {JOY_EVENT_INPUT, BTN_START, 10}, // [239]
    {JOY_EVENT_INPUT, 0, 30},          // [240]

    {JOY_EVENT_INPUT, BTN_DOWN, 10},  // [241]
    {JOY_EVENT_INPUT, 0, 30},          // [242]

    {JOY_EVENT_INPUT, BTN_START, 10}, // [243]
    {JOY_EVENT_INPUT, 0, 9600},          // [242]
    {JOY_EVENT_RESET, 0, 0},
    {JOY_EVENT_INPUT, 0, 30},          // [242]
    {JOY_EVENT_INPUT, BTN_START, 10},
    {JOY_EVENT_INPUT, 0, 10},
    {JOY_EVENT_INPUT, BTN_DOWN, 10},
    {JOY_EVENT_INPUT, 0, 10},
    {JOY_EVENT_INPUT, BTN_DOWN, 10},
    {JOY_EVENT_INPUT, BTN_DOWN, 10},
    {JOY_EVENT_INPUT, 0, 10},
    {JOY_EVENT_INPUT, BTN_DOWN, 10},
    {JOY_EVENT_INPUT, 0, 10},
    {JOY_EVENT_INPUT, BTN_DOWN, 10},

    {JOY_EVENT_INPUT, BTN_START, 10},
    {JOY_EVENT_INPUT, BTN_DOWN, 10},
    {JOY_EVENT_INPUT, BTN_START, 10},
    {JOY_EVENT_INPUT, BTN_UP, 10},
    {JOY_EVENT_INPUT, 0, 10},

    {JOY_EVENT_INPUT, BTN_UP, 10},
    {JOY_EVENT_INPUT, BTN_START, 10},
    {JOY_EVENT_INPUT, 0, 77},
    {JOY_EVENT_INPUT, BTN_START, 6},
    {JOY_EVENT_INPUT, 0, 40},
    {JOY_EVENT_INPUT, BTN_RIGHT, 5},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 7},
    {JOY_EVENT_INPUT, BTN_RIGHT, 1},
    {JOY_EVENT_INPUT, 0, 19},
    {JOY_EVENT_INPUT, BTN_START, 8},
    {JOY_EVENT_INPUT, 0, 164},
    {JOY_EVENT_INPUT, BTN_RIGHT, 6},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 85},
    {JOY_EVENT_INPUT, BTN_B, 17},
    {JOY_EVENT_INPUT, BTN_B | BTN_A, 3},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_B | BTN_A, 3},
    {JOY_EVENT_INPUT, BTN_B | BTN_A, 7},
    {JOY_EVENT_INPUT, BTN_B, 7},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_B, 7},
    {JOY_EVENT_INPUT, BTN_B, 6},
    {JOY_EVENT_INPUT, BTN_B | BTN_A, 3},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B | BTN_A, 7},
    {JOY_EVENT_INPUT, BTN_B | BTN_A, 4},
    {JOY_EVENT_INPUT, BTN_B, 30},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 14},
    {JOY_EVENT_INPUT, BTN_B, 8},
    {JOY_EVENT_INPUT, BTN_B | BTN_A, 3},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_B | BTN_A, 14},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_B, 30},
    {JOY_EVENT_INPUT, BTN_B, 4},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B | BTN_A, 18},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 32},
    {JOY_EVENT_INPUT, BTN_B, 6},
    {JOY_EVENT_INPUT, BTN_B | BTN_A, 15},
    {JOY_EVENT_INPUT, BTN_B, 17},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_B, 24},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_B | BTN_A, 1},
    {JOY_EVENT_INPUT, BTN_B | BTN_A, 3},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B | BTN_A, 17},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 51},
    {JOY_EVENT_INPUT, BTN_B, 9},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_B, 25},
    {JOY_EVENT_INPUT, BTN_B, 7},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_B, 20},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_B | BTN_A, 28},
    {JOY_EVENT_INPUT, BTN_B | BTN_A, 1},
    {JOY_EVENT_INPUT, BTN_B, 12},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_B, 7},
    {JOY_EVENT_INPUT, BTN_B, 13},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_B, 6},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_B | BTN_A, 39},
    {JOY_EVENT_INPUT, BTN_B | BTN_A, 3},
    {JOY_EVENT_INPUT, BTN_B, 5},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 11},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B | BTN_A, 2},
    {JOY_EVENT_INPUT, BTN_B | BTN_A, 5},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_B | BTN_A, 4},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_B, 8},
    {JOY_EVENT_INPUT, BTN_B, 3},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 41},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B | BTN_A, 8},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 19},
    {JOY_EVENT_INPUT, BTN_B, 13},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 29},
    {JOY_EVENT_INPUT, BTN_B, 5},
    {JOY_EVENT_INPUT, BTN_B | BTN_A, 11},
    {JOY_EVENT_INPUT, BTN_B, 4},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_B, 5},
    {JOY_EVENT_INPUT, BTN_B, 20},
    {JOY_EVENT_INPUT, BTN_B | BTN_A, 7},
    {JOY_EVENT_INPUT, BTN_B, 5},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_B, 5},
    {JOY_EVENT_INPUT, BTN_B, 13},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 19},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B | BTN_A, 8},
    {JOY_EVENT_INPUT, BTN_B | BTN_A, 15},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_B, 8},
    {JOY_EVENT_INPUT, BTN_B, 9},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B | BTN_A, 11},
    {JOY_EVENT_INPUT, BTN_B, 4},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_B, 17},
    {JOY_EVENT_INPUT, BTN_B, 13},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_B, 29},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_B | BTN_A, 11},
    {JOY_EVENT_INPUT, BTN_B | BTN_A, 4},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B | BTN_A, 2},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 43},
    {JOY_EVENT_INPUT, BTN_B, 12},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 9},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B | BTN_A, 29},
    {JOY_EVENT_INPUT, BTN_B | BTN_A, 2},
    {JOY_EVENT_INPUT, BTN_B, 12},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_B, 18},
    {JOY_EVENT_INPUT, BTN_B, 14},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_B, 5},
    {JOY_EVENT_INPUT, BTN_B | BTN_A, 2},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B | BTN_A, 43},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 18},
    {JOY_EVENT_INPUT, BTN_B, 7},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_B, 9},
    {JOY_EVENT_INPUT, BTN_B, 3},
    {JOY_EVENT_INPUT, BTN_B | BTN_A, 7},
    {JOY_EVENT_INPUT, BTN_B, 12},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_B, 9},
    {JOY_EVENT_INPUT, BTN_B, 12},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 25},
    {JOY_EVENT_INPUT, BTN_B, 2},
    {JOY_EVENT_INPUT, BTN_B | BTN_A, 7},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_B | BTN_A, 29},
    {JOY_EVENT_INPUT, BTN_B, 1},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_B, 8},
    {JOY_EVENT_INPUT, BTN_B, 6},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 15},
    {JOY_EVENT_INPUT, BTN_B, 9},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 22},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B | BTN_A, 21},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 48},
    {JOY_EVENT_INPUT, BTN_B, 23},
    {JOY_EVENT_INPUT, BTN_B | BTN_A, 11},
    {JOY_EVENT_INPUT, BTN_B, 15},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_B, 10},
    {JOY_EVENT_INPUT, BTN_B, 5},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 17},
    {JOY_EVENT_INPUT, BTN_B, 7},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_B, 7},
    {JOY_EVENT_INPUT, BTN_B, 5},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 12},
    {JOY_EVENT_INPUT, BTN_B, 5},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_B, 1},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_B | BTN_A, 39},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_B, 11},
    {JOY_EVENT_INPUT, BTN_B, 12},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 9},
    {JOY_EVENT_INPUT, BTN_B, 8},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 32},
    {JOY_EVENT_INPUT, BTN_B, 7},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 20},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B | BTN_A, 7},
    {JOY_EVENT_INPUT, BTN_B | BTN_A, 8},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B | BTN_A, 24},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 1},
    {JOY_EVENT_INPUT, BTN_RIGHT, 5},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 7},
    {JOY_EVENT_INPUT, BTN_RIGHT, 4},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 5},
    {JOY_EVENT_INPUT, BTN_RIGHT, 4},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 5},
    {JOY_EVENT_INPUT, BTN_RIGHT, 5},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 7},
    {JOY_EVENT_INPUT, BTN_RIGHT, 10},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_A, 2},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B | BTN_A, 19},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 53},
    {JOY_EVENT_INPUT, BTN_B, 6},
    {JOY_EVENT_INPUT, 0, 3},
    {JOY_EVENT_INPUT, BTN_B, 7},
    {JOY_EVENT_INPUT, 0, 3},
    {JOY_EVENT_INPUT, BTN_B, 5},
    {JOY_EVENT_INPUT, 0, 2},
    {JOY_EVENT_INPUT, BTN_RIGHT, 2},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 5},
    {JOY_EVENT_INPUT, BTN_RIGHT, 4},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 4},
    {JOY_EVENT_INPUT, BTN_RIGHT, 13},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 47},
    {JOY_EVENT_INPUT, BTN_RIGHT, 5},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 6},
    {JOY_EVENT_INPUT, BTN_RIGHT, 4},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 6},
    {JOY_EVENT_INPUT, BTN_RIGHT, 8},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 3},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B | BTN_A, 11},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 22},
    {JOY_EVENT_INPUT, BTN_RIGHT, 3},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 6},
    {JOY_EVENT_INPUT, BTN_RIGHT, 4},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 5},
    {JOY_EVENT_INPUT, BTN_RIGHT, 11},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 52},
    {JOY_EVENT_INPUT, BTN_RIGHT, 4},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 6},
    {JOY_EVENT_INPUT, BTN_RIGHT, 2},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 6},
    {JOY_EVENT_INPUT, BTN_RIGHT, 2},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 7},
    {JOY_EVENT_INPUT, BTN_RIGHT, 3},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 5},
    {JOY_EVENT_INPUT, BTN_RIGHT, 4},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 5},
    {JOY_EVENT_INPUT, BTN_RIGHT, 4},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 6},
    {JOY_EVENT_INPUT, BTN_RIGHT, 2},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 8},
    {JOY_EVENT_INPUT, BTN_RIGHT, 17},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 25},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B | BTN_A, 20},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 15},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B | BTN_A, 30},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 12},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B | BTN_A, 10},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 5},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B | BTN_A, 30},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 9},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B | BTN_A, 37},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 39},
    {JOY_EVENT_INPUT, 0, 10},
    {JOY_EVENT_RESET, 0, 0},
    {JOY_EVENT_INPUT, 0, 10},
    {JOY_EVENT_INPUT, BTN_DOWN, 10},
    {JOY_EVENT_INPUT, 0, 10},
    {JOY_EVENT_INPUT, BTN_DOWN, 10},
    {JOY_EVENT_INPUT, 0, 10},
    {JOY_EVENT_INPUT, BTN_DOWN, 10},
    {JOY_EVENT_INPUT, 0, 10},
    {JOY_EVENT_INPUT, BTN_DOWN, 10},
    {JOY_EVENT_INPUT, 0, 10},
    {JOY_EVENT_INPUT, BTN_DOWN, 10},
    {JOY_EVENT_INPUT, 0, 10},
    {JOY_EVENT_INPUT, BTN_DOWN, 10},
    {JOY_EVENT_INPUT, 0, 10},
    {JOY_EVENT_INPUT, BTN_DOWN, 10},
    {JOY_EVENT_INPUT, 0, 10},
    {JOY_EVENT_INPUT, BTN_DOWN, 10},
    {JOY_EVENT_INPUT, 0, 10},
    {JOY_EVENT_INPUT, BTN_DOWN, 10},
    {JOY_EVENT_INPUT, 0, 10},
    {JOY_EVENT_INPUT, BTN_DOWN, 10},
    {JOY_EVENT_INPUT, 0, 10},
    {JOY_EVENT_INPUT, BTN_DOWN, 10},
    {JOY_EVENT_INPUT, 0, 10},
    {JOY_EVENT_INPUT, BTN_DOWN, 10},
    {JOY_EVENT_INPUT, 0, 10},
    {JOY_EVENT_INPUT, BTN_DOWN, 10},
    {JOY_EVENT_INPUT, 0, 10},
    {JOY_EVENT_INPUT, BTN_START, 10},
    {JOY_EVENT_INPUT, 0, 43},
    {JOY_EVENT_INPUT, BTN_START, 5},
    {JOY_EVENT_INPUT, 0, 544},
    {JOY_EVENT_INPUT, BTN_RIGHT, 67},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_A, 19},
    {JOY_EVENT_INPUT, BTN_RIGHT, 26},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 42},
    {JOY_EVENT_INPUT, BTN_RIGHT, 85},
    {JOY_EVENT_INPUT, BTN_UP | BTN_RIGHT, 5},
    {JOY_EVENT_INPUT, BTN_UP, 19},
    {JOY_EVENT_INPUT, 0, 2},
    {JOY_EVENT_INPUT, BTN_LEFT, 8},
    {JOY_EVENT_INPUT, 0, 1},
    {JOY_EVENT_INPUT, BTN_UP, 75},
    {JOY_EVENT_INPUT, BTN_UP | BTN_LEFT, 2},
    {JOY_EVENT_INPUT, BTN_LEFT, 47},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_A, 11},
    {JOY_EVENT_INPUT, BTN_LEFT, 86},
    {JOY_EVENT_INPUT, BTN_UP, 88},
    {JOY_EVENT_INPUT, BTN_LEFT, 100},
    {JOY_EVENT_INPUT, 0, 2},
    {JOY_EVENT_INPUT, BTN_LEFT, 6},
    {JOY_EVENT_INPUT, 0, 9},
    {JOY_EVENT_INPUT, BTN_LEFT, 10},
    {JOY_EVENT_INPUT, 0, 5},
    {JOY_EVENT_INPUT, BTN_A, 7},
    {JOY_EVENT_INPUT, 0, 42},
    {JOY_EVENT_INPUT, BTN_B, 2},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 7},
    {JOY_EVENT_INPUT, BTN_RIGHT, 5},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 4},
    {JOY_EVENT_INPUT, BTN_B, 7},
    {JOY_EVENT_INPUT, 0, 1},
    {JOY_EVENT_INPUT, BTN_RIGHT, 397},
    {JOY_EVENT_INPUT, 0, 1},
    {JOY_EVENT_INPUT, BTN_UP, 24},
    {JOY_EVENT_INPUT, 0, 2},
    {JOY_EVENT_INPUT, BTN_LEFT, 5},
    {JOY_EVENT_INPUT, 0, 4},
    {JOY_EVENT_INPUT, BTN_UP, 24},
    {JOY_EVENT_INPUT, 0, 49},
    {JOY_EVENT_INPUT, BTN_UP, 62},
    {JOY_EVENT_INPUT, 0, 6},
    {JOY_EVENT_INPUT, BTN_UP, 4},
    {JOY_EVENT_INPUT, BTN_UP | BTN_LEFT, 2},
    {JOY_EVENT_INPUT, BTN_UP, 4},
    {JOY_EVENT_INPUT, 0, 11},
    {JOY_EVENT_INPUT, BTN_UP, 53},
    {JOY_EVENT_INPUT, 0, 66},
    {JOY_EVENT_INPUT, BTN_LEFT, 11},
    {JOY_EVENT_INPUT, 0, 11},
    {JOY_EVENT_INPUT, BTN_RIGHT, 9},
    {JOY_EVENT_INPUT, 0, 7},
    {JOY_EVENT_INPUT, BTN_UP, 22},
    {JOY_EVENT_INPUT, 0, 11},
    {JOY_EVENT_INPUT, BTN_RIGHT, 8},
    {JOY_EVENT_INPUT, BTN_LEFT, 40},
    {JOY_EVENT_INPUT, 0, 2},
    {JOY_EVENT_INPUT, BTN_RIGHT, 31},
    {JOY_EVENT_INPUT, 0, 2},
    {JOY_EVENT_INPUT, BTN_UP, 17},
    {JOY_EVENT_INPUT, 0, 71},
    {JOY_EVENT_INPUT, BTN_UP, 60},
    {JOY_EVENT_INPUT, BTN_LEFT, 45},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_A, 38},
    {JOY_EVENT_INPUT, BTN_LEFT, 93},
    {JOY_EVENT_INPUT, BTN_UP, 86},
    {JOY_EVENT_INPUT, BTN_UP | BTN_RIGHT, 2},
    {JOY_EVENT_INPUT, BTN_RIGHT, 21},
    {JOY_EVENT_INPUT, 0, 12},
    {JOY_EVENT_INPUT, BTN_RIGHT, 12},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_A, 20},
    {JOY_EVENT_INPUT, BTN_RIGHT, 86},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_A, 29},
    {JOY_EVENT_INPUT, BTN_A, 3},
    {JOY_EVENT_INPUT, BTN_LEFT, 6},
    {JOY_EVENT_INPUT, 0, 2},
    {JOY_EVENT_INPUT, BTN_UP, 7},
    {JOY_EVENT_INPUT, BTN_UP | BTN_RIGHT, 3},
    {JOY_EVENT_INPUT, BTN_RIGHT, 9},
    {JOY_EVENT_INPUT, 0, 8},
    {JOY_EVENT_INPUT, BTN_UP, 12},
    {JOY_EVENT_INPUT, 0, 1},
    {JOY_EVENT_INPUT, BTN_RIGHT, 6},
    {JOY_EVENT_INPUT, 0, 48},
    {JOY_EVENT_INPUT, BTN_UP, 66},
    {JOY_EVENT_INPUT, BTN_LEFT, 51},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_A, 28},
    {JOY_EVENT_INPUT, BTN_LEFT, 6},
    {JOY_EVENT_INPUT, 0, 14},
    {JOY_EVENT_INPUT, BTN_LEFT, 6},
    {JOY_EVENT_INPUT, 0, 4},
    {JOY_EVENT_INPUT, BTN_UP, 100},
    {JOY_EVENT_INPUT, 0, 443},

    {JOY_EVENT_RESET, 0, 0},
    {JOY_EVENT_INPUT, 0, 10},
    {JOY_EVENT_INPUT, BTN_START, 10},
    {JOY_EVENT_INPUT, 0, 10},
    {JOY_EVENT_INPUT, BTN_DOWN, 10},
    {JOY_EVENT_INPUT, 0, 10},
    {JOY_EVENT_INPUT, BTN_DOWN, 10},
    {JOY_EVENT_INPUT, 0, 10},
    {JOY_EVENT_INPUT, BTN_DOWN, 10},
    {JOY_EVENT_INPUT, 0, 10},
    {JOY_EVENT_INPUT, BTN_START, 10},
    {JOY_EVENT_INPUT, 0, 10},
    {JOY_EVENT_INPUT, BTN_UP, 10},
    {JOY_EVENT_INPUT, 0, 10},
    {JOY_EVENT_INPUT, BTN_START, 10},

    {JOY_EVENT_INPUT, 0, 1806},
    {JOY_EVENT_INPUT, BTN_START, 8},
    {JOY_EVENT_INPUT, 0, 14},
    {JOY_EVENT_INPUT, BTN_START, 8},
    {JOY_EVENT_INPUT, 0, 40},
    {JOY_EVENT_INPUT, BTN_START, 7},
    {JOY_EVENT_INPUT, 0, 43},
    {JOY_EVENT_INPUT, BTN_START, 8},
    {JOY_EVENT_INPUT, 0, 165},
    {JOY_EVENT_INPUT, BTN_RIGHT, 10},
    {JOY_EVENT_INPUT, 0, 126},
    {JOY_EVENT_INPUT, BTN_RIGHT, 5},
    {JOY_EVENT_INPUT, 0, 16},
    {JOY_EVENT_INPUT, BTN_UP, 6},
    {JOY_EVENT_INPUT, 0, 64},
    {JOY_EVENT_INPUT, BTN_START, 11},
    {JOY_EVENT_INPUT, 0, 16},
    {JOY_EVENT_INPUT, BTN_A, 11},
    {JOY_EVENT_INPUT, 0, 92},
    {JOY_EVENT_INPUT, BTN_RIGHT, 3},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 39},
    {JOY_EVENT_INPUT, BTN_B, 17},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 9},
    {JOY_EVENT_INPUT, BTN_B, 3},
    {JOY_EVENT_INPUT, BTN_B | BTN_A, 16},
    {JOY_EVENT_INPUT, BTN_B, 1},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_B, 15},
    {JOY_EVENT_INPUT, BTN_B, 31},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 26},
    {JOY_EVENT_INPUT, BTN_B, 12},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 7},
    {JOY_EVENT_INPUT, BTN_B, 8},
    {JOY_EVENT_INPUT, BTN_B | BTN_A, 12},
    {JOY_EVENT_INPUT, BTN_B, 24},
    {JOY_EVENT_INPUT, BTN_B | BTN_A, 13},
    {JOY_EVENT_INPUT, BTN_B, 17},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 14},
    {JOY_EVENT_INPUT, BTN_B, 5},
    {JOY_EVENT_INPUT, BTN_B | BTN_A, 7},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B | BTN_A, 13},
    {JOY_EVENT_INPUT, BTN_B, 10},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_B, 16},
    {JOY_EVENT_INPUT, BTN_B, 7},
    {JOY_EVENT_INPUT, BTN_B | BTN_A, 16},
    {JOY_EVENT_INPUT, BTN_B, 18},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 18},
    {JOY_EVENT_INPUT, BTN_B | BTN_A, 13},
    {JOY_EVENT_INPUT, BTN_B, 11},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_B, 17},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_B | BTN_A, 22},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_B, 21},
    {JOY_EVENT_INPUT, BTN_B, 13},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 67},
    {JOY_EVENT_INPUT, BTN_B, 18},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 9},
    {JOY_EVENT_INPUT, BTN_B, 33},
    {JOY_EVENT_INPUT, BTN_B | BTN_A, 4},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B | BTN_A, 17},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 41},
    {JOY_EVENT_INPUT, BTN_B, 25},
    {JOY_EVENT_INPUT, BTN_B | BTN_A, 6},
    {JOY_EVENT_INPUT, BTN_B, 6},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_B, 8},
    {JOY_EVENT_INPUT, BTN_B, 7},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 14},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B | BTN_A, 35},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 1},
    {JOY_EVENT_INPUT, BTN_B, 9},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_B, 12},
    {JOY_EVENT_INPUT, BTN_B, 17},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 6},
    {JOY_EVENT_INPUT, BTN_B, 2},
    {JOY_EVENT_INPUT, BTN_B | BTN_A, 10},
    {JOY_EVENT_INPUT, BTN_B, 5},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 20},
    {JOY_EVENT_INPUT, BTN_B | BTN_A, 8},
    {JOY_EVENT_INPUT, BTN_B, 21},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 12},
    {JOY_EVENT_INPUT, BTN_B, 7},
    {JOY_EVENT_INPUT, BTN_B | BTN_A, 6},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B | BTN_A, 2},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 9},
    {JOY_EVENT_INPUT, BTN_B, 8},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_B, 8},
    {JOY_EVENT_INPUT, BTN_B, 46},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_B, 12},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_B | BTN_A, 8},
    {JOY_EVENT_INPUT, BTN_B, 6},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_B, 12},
    {JOY_EVENT_INPUT, BTN_B, 15},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 53},
    {JOY_EVENT_INPUT, BTN_B, 24},
    {JOY_EVENT_INPUT, 0, 32},
    {JOY_EVENT_INPUT, BTN_A, 2},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_A, 37},
    {JOY_EVENT_INPUT, BTN_RIGHT, 3},
    {JOY_EVENT_INPUT, 0, 6},
    {JOY_EVENT_INPUT, BTN_RIGHT, 18},
    {JOY_EVENT_INPUT, 0, 23},
    {JOY_EVENT_INPUT, BTN_RIGHT, 17},
    {JOY_EVENT_INPUT, 0, 15},
    {JOY_EVENT_INPUT, BTN_B, 30},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 3},
    {JOY_EVENT_INPUT, BTN_RIGHT, 4},
    {JOY_EVENT_INPUT, 0, 5},
    {JOY_EVENT_INPUT, BTN_LEFT, 18},
    {JOY_EVENT_INPUT, 0, 1},
    {JOY_EVENT_INPUT, BTN_A, 3},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_A, 5},
    {JOY_EVENT_INPUT, BTN_RIGHT, 36},
    {JOY_EVENT_INPUT, 0, 7},
    {JOY_EVENT_INPUT, BTN_B, 11},
    {JOY_EVENT_INPUT, 0, 18},
    {JOY_EVENT_INPUT, BTN_RIGHT, 6},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 35},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B | BTN_A, 24},
    {JOY_EVENT_INPUT, BTN_B | BTN_A, 1},
    {JOY_EVENT_INPUT, BTN_B, 3},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_B, 33},
    {JOY_EVENT_INPUT, BTN_B, 5},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 7},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B | BTN_A, 46},
    {JOY_EVENT_INPUT, BTN_B | BTN_A, 5},
    {JOY_EVENT_INPUT, BTN_B, 33},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 20},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B | BTN_A, 44},
    {JOY_EVENT_INPUT, BTN_B | BTN_A, 1},
    {JOY_EVENT_INPUT, BTN_B, 37},
    {JOY_EVENT_INPUT, BTN_B | BTN_A, 3},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B | BTN_A, 8},
    {JOY_EVENT_INPUT, BTN_B, 17},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 15},
    {JOY_EVENT_INPUT, BTN_B, 50},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 1},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B | BTN_A, 5},
    {JOY_EVENT_INPUT, BTN_B | BTN_A, 2},
    {JOY_EVENT_INPUT, BTN_B, 21},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 20},
    {JOY_EVENT_INPUT, BTN_B, 36},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 9},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B | BTN_A, 13},
    {JOY_EVENT_INPUT, BTN_B | BTN_A, 2},
    {JOY_EVENT_INPUT, BTN_B, 24},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 6},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B | BTN_A, 17},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 3},
    {JOY_EVENT_INPUT, BTN_B, 40},
    {JOY_EVENT_INPUT, BTN_B | BTN_A, 7},
    {JOY_EVENT_INPUT, BTN_B, 45},
    {JOY_EVENT_INPUT, BTN_B | BTN_A, 8},
    {JOY_EVENT_INPUT, BTN_B, 3},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 14},
    {JOY_EVENT_INPUT, BTN_B, 12},
    {JOY_EVENT_INPUT, BTN_B | BTN_A, 8},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 7},
    {JOY_EVENT_INPUT, BTN_B, 21},
    {JOY_EVENT_INPUT, BTN_B | BTN_A, 1},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B | BTN_A, 39},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 7},
    {JOY_EVENT_INPUT, BTN_B, 1},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 5},
    {JOY_EVENT_INPUT, BTN_B, 90},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 2},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B | BTN_A, 12},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 2},
    {JOY_EVENT_INPUT, BTN_B, 18},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 14},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B | BTN_A, 39},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 1},
    {JOY_EVENT_INPUT, BTN_B, 29},
    {JOY_EVENT_INPUT, BTN_B | BTN_A, 9},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B | BTN_A, 33},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 5},
    {JOY_EVENT_INPUT, BTN_B, 29},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 9},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B | BTN_A, 19},
    {JOY_EVENT_INPUT, BTN_B | BTN_A, 2},
    {JOY_EVENT_INPUT, BTN_B, 10},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_B, 9},
    {JOY_EVENT_INPUT, BTN_B, 25},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_B, 13},
    {JOY_EVENT_INPUT, BTN_B, 24},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 10},
    {JOY_EVENT_INPUT, BTN_B, 28},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 43},
    {JOY_EVENT_INPUT, BTN_B, 13},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 10},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B | BTN_A, 18},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 1},
    {JOY_EVENT_INPUT, BTN_B, 59},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B | BTN_A, 23},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 25},
    {JOY_EVENT_INPUT, BTN_B, 33},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 91},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B | BTN_A, 19},
    {JOY_EVENT_INPUT, BTN_B | BTN_A, 4},
    {JOY_EVENT_INPUT, BTN_B, 28},
    {JOY_EVENT_INPUT, 0, 499},
    {JOY_EVENT_INPUT, BTN_RIGHT, 9},
    {JOY_EVENT_INPUT, 0, 18},
    {JOY_EVENT_INPUT, BTN_RIGHT, 9},
    {JOY_EVENT_INPUT, 0, 228},
    {JOY_EVENT_RESET, 0, 0},

    {JOY_EVENT_INPUT, 0, 20},
    {JOY_EVENT_INPUT, BTN_START, 20},
    {JOY_EVENT_INPUT, 0, 20},
    {JOY_EVENT_INPUT, BTN_DOWN, 10},
    {JOY_EVENT_INPUT, 0, 20},
    {JOY_EVENT_INPUT, BTN_DOWN, 10},
    {JOY_EVENT_INPUT, 0, 20},
    {JOY_EVENT_INPUT, BTN_START, 20},
    {JOY_EVENT_INPUT, 0, 20},
    {JOY_EVENT_INPUT, BTN_UP, 20},
    {JOY_EVENT_INPUT, 0, 20},
    {JOY_EVENT_INPUT, BTN_UP, 20},
    {JOY_EVENT_INPUT, 0, 20},
    {JOY_EVENT_INPUT, BTN_UP, 20},
    {JOY_EVENT_INPUT, 0, 20},
    {JOY_EVENT_INPUT, BTN_UP, 20},
    {JOY_EVENT_INPUT, 0, 20},
    {JOY_EVENT_INPUT, BTN_UP, 20},
    {JOY_EVENT_INPUT, 0, 20},
    {JOY_EVENT_INPUT, BTN_UP, 20},
    {JOY_EVENT_INPUT, 0, 20},
    {JOY_EVENT_INPUT, BTN_UP, 20},
    {JOY_EVENT_INPUT, 0, 20},
    {JOY_EVENT_INPUT, BTN_START, 20},
    {JOY_EVENT_INPUT, 0, 50},
    {JOY_EVENT_INPUT, 0, 522},
    {JOY_EVENT_INPUT, BTN_START, 7},
    {JOY_EVENT_INPUT, 0, 568},
    {JOY_EVENT_INPUT, BTN_RIGHT, 52},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_START, 10},
    {JOY_EVENT_INPUT, BTN_RIGHT, 16},
    {JOY_EVENT_INPUT, 0, 24},
    {JOY_EVENT_INPUT, BTN_START, 10},
    {JOY_EVENT_INPUT, 0, 8},
    {JOY_EVENT_INPUT, BTN_RIGHT, 13},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 12},
    {JOY_EVENT_INPUT, BTN_RIGHT, 13},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 11},
    {JOY_EVENT_INPUT, BTN_RIGHT, 17},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 8},
    {JOY_EVENT_INPUT, BTN_RIGHT, 9},
    {JOY_EVENT_INPUT, 0, 22},
    {JOY_EVENT_INPUT, BTN_RIGHT, 18},
    {JOY_EVENT_INPUT, BTN_DOWN | BTN_RIGHT, 1},
    {JOY_EVENT_INPUT, BTN_DOWN, 21},
    {JOY_EVENT_INPUT, 0, 3},
    {JOY_EVENT_INPUT, BTN_B, 8},
    {JOY_EVENT_INPUT, 0, 2},
    {JOY_EVENT_INPUT, BTN_DOWN, 19},
    {JOY_EVENT_INPUT, BTN_DOWN | BTN_B, 7},
    {JOY_EVENT_INPUT, BTN_DOWN, 5},
    {JOY_EVENT_INPUT, 0, 1},
    {JOY_EVENT_INPUT, BTN_DOWN | BTN_RIGHT, 5},
    {JOY_EVENT_INPUT, BTN_DOWN, 13},
    {JOY_EVENT_INPUT, 0, 3},
    {JOY_EVENT_INPUT, BTN_RIGHT, 29},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 6},
    {JOY_EVENT_INPUT, BTN_RIGHT, 16},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 6},
    {JOY_EVENT_INPUT, BTN_RIGHT, 27},
    {JOY_EVENT_INPUT, BTN_DOWN | BTN_RIGHT, 1},
    {JOY_EVENT_INPUT, BTN_DOWN, 12},
    {JOY_EVENT_INPUT, BTN_DOWN | BTN_B, 9},
    {JOY_EVENT_INPUT, BTN_DOWN, 5},
    {JOY_EVENT_INPUT, 0, 1},
    {JOY_EVENT_INPUT, BTN_RIGHT, 33},
    {JOY_EVENT_INPUT, BTN_UP | BTN_RIGHT, 1},
    {JOY_EVENT_INPUT, BTN_UP, 22},
    {JOY_EVENT_INPUT, 0, 2},
    {JOY_EVENT_INPUT, BTN_RIGHT, 62},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_A, 14},
    {JOY_EVENT_INPUT, BTN_DOWN | BTN_RIGHT | BTN_A, 1},
    {JOY_EVENT_INPUT, BTN_DOWN | BTN_RIGHT, 4},
    {JOY_EVENT_INPUT, BTN_RIGHT, 1},
    {JOY_EVENT_INPUT, BTN_DOWN | BTN_RIGHT, 13},
    {JOY_EVENT_INPUT, BTN_DOWN, 41},
    {JOY_EVENT_INPUT, BTN_DOWN | BTN_RIGHT, 9},
    {JOY_EVENT_INPUT, BTN_RIGHT, 38},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_A, 2},
    {JOY_EVENT_INPUT, BTN_LEFT | BTN_A, 6},
    {JOY_EVENT_INPUT, BTN_LEFT, 2},
    {JOY_EVENT_INPUT, BTN_B, 10},
    {JOY_EVENT_INPUT, 0, 13},
    {JOY_EVENT_INPUT, BTN_RIGHT, 24},
    {JOY_EVENT_INPUT, 0, 14},
    {JOY_EVENT_INPUT, BTN_RIGHT, 9},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 13},
    {JOY_EVENT_INPUT, BTN_RIGHT, 16},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_A, 13},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 12},
    {JOY_EVENT_INPUT, BTN_RIGHT, 116},
    {JOY_EVENT_INPUT, 0, 2},
    {JOY_EVENT_INPUT, BTN_DOWN, 12},
    {JOY_EVENT_INPUT, BTN_DOWN | BTN_A, 12},
    {JOY_EVENT_INPUT, BTN_DOWN | BTN_RIGHT | BTN_A, 3},
    {JOY_EVENT_INPUT, BTN_DOWN | BTN_RIGHT, 19},
    {JOY_EVENT_INPUT, BTN_DOWN, 8},
    {JOY_EVENT_INPUT, BTN_DOWN | BTN_LEFT, 4},
    {JOY_EVENT_INPUT, BTN_LEFT, 14},
    {JOY_EVENT_INPUT, BTN_DOWN | BTN_LEFT, 3},
    {JOY_EVENT_INPUT, BTN_DOWN, 4},
    {JOY_EVENT_INPUT, BTN_DOWN | BTN_A, 13},
    {JOY_EVENT_INPUT, BTN_DOWN, 17},
    {JOY_EVENT_INPUT, BTN_DOWN | BTN_B, 5},
    {JOY_EVENT_INPUT, BTN_B, 4},
    {JOY_EVENT_INPUT, 0, 25},
    {JOY_EVENT_INPUT, BTN_B, 10},
    {JOY_EVENT_INPUT, 0, 10},
    {JOY_EVENT_INPUT, BTN_UP, 6},
    {JOY_EVENT_INPUT, BTN_UP | BTN_A, 10},
    {JOY_EVENT_INPUT, BTN_UP | BTN_RIGHT | BTN_A, 4},
    {JOY_EVENT_INPUT, BTN_UP | BTN_RIGHT, 7},
    {JOY_EVENT_INPUT, BTN_RIGHT, 42},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_A, 7},
    {JOY_EVENT_INPUT, BTN_RIGHT, 80},
    {JOY_EVENT_INPUT, 0, 23},
    {JOY_EVENT_INPUT, BTN_RIGHT, 68},
    {JOY_EVENT_INPUT, BTN_DOWN | BTN_RIGHT, 2},
    {JOY_EVENT_INPUT, BTN_DOWN | BTN_RIGHT | BTN_A, 27},
    {JOY_EVENT_INPUT, BTN_DOWN | BTN_RIGHT, 10},
    {JOY_EVENT_INPUT, BTN_RIGHT, 522},
    {JOY_EVENT_INPUT, BTN_UP | BTN_RIGHT, 1},
    {JOY_EVENT_INPUT, BTN_UP, 8},
    {JOY_EVENT_INPUT, BTN_UP | BTN_B, 11},
    {JOY_EVENT_INPUT, BTN_UP, 13},
    {JOY_EVENT_INPUT, BTN_UP | BTN_RIGHT, 3},
    {JOY_EVENT_INPUT, BTN_RIGHT, 72},
    {JOY_EVENT_INPUT, BTN_UP | BTN_RIGHT, 1},
    {JOY_EVENT_INPUT, BTN_UP, 10},
    {JOY_EVENT_INPUT, BTN_UP | BTN_B, 10},
    {JOY_EVENT_INPUT, BTN_UP, 27},
    {JOY_EVENT_INPUT, BTN_RIGHT, 21},
    {JOY_EVENT_INPUT, BTN_UP, 21},
    {JOY_EVENT_INPUT, 0, 1},
    {JOY_EVENT_INPUT, BTN_RIGHT, 26},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_A, 19},
    {JOY_EVENT_INPUT, BTN_RIGHT, 8},
    {JOY_EVENT_INPUT, BTN_UP | BTN_RIGHT, 3},
    {JOY_EVENT_INPUT, BTN_UP, 2},
    {JOY_EVENT_INPUT, BTN_UP | BTN_RIGHT, 5},
    {JOY_EVENT_INPUT, BTN_RIGHT, 3},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_A, 11},
    {JOY_EVENT_INPUT, BTN_RIGHT, 42},
    {JOY_EVENT_INPUT, BTN_UP | BTN_RIGHT, 9},
    {JOY_EVENT_INPUT, BTN_UP | BTN_RIGHT | BTN_A, 29},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_A, 3},
    {JOY_EVENT_INPUT, BTN_RIGHT, 26},
    {JOY_EVENT_INPUT, 0, 12},
    {JOY_EVENT_INPUT, BTN_UP, 5},
    {JOY_EVENT_INPUT, 0, 4},
    {JOY_EVENT_INPUT, BTN_RIGHT, 5},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_B, 12},
    {JOY_EVENT_INPUT, BTN_RIGHT, 12},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_A, 37},
    {JOY_EVENT_INPUT, BTN_RIGHT, 13},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_A, 15},
    {JOY_EVENT_INPUT, BTN_RIGHT, 5},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_A, 31},
    {JOY_EVENT_INPUT, BTN_RIGHT, 48},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_A, 12},
    {JOY_EVENT_INPUT, BTN_UP | BTN_RIGHT | BTN_A, 27},
    {JOY_EVENT_INPUT, BTN_UP | BTN_RIGHT, 8},
    {JOY_EVENT_INPUT, BTN_RIGHT, 31},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_A, 52},
    {JOY_EVENT_INPUT, BTN_RIGHT, 52},
    {JOY_EVENT_INPUT, BTN_RIGHT | BTN_A, 27},
    {JOY_EVENT_INPUT, BTN_RIGHT, 27},
    {JOY_EVENT_INPUT, BTN_UP, 4},
    {JOY_EVENT_INPUT, BTN_UP | BTN_A, 35},
    {JOY_EVENT_INPUT, BTN_UP, 1},
    {JOY_EVENT_INPUT, 0, 2},
    {JOY_EVENT_INPUT, BTN_RIGHT, 22},
    {JOY_EVENT_INPUT, 0, 9},
    {JOY_EVENT_INPUT, BTN_A, 8},
    {JOY_EVENT_INPUT, BTN_UP | BTN_A, 4},
    {JOY_EVENT_INPUT, BTN_UP, 4},
    {JOY_EVENT_INPUT, 0, 3},
    {JOY_EVENT_INPUT, BTN_A, 2},
    {JOY_EVENT_INPUT, BTN_UP | BTN_A, 11},
    {JOY_EVENT_INPUT, BTN_UP, 2},
    {JOY_EVENT_INPUT, 0, 20},
    {JOY_EVENT_INPUT, 0, 20},
    {JOY_EVENT_RESET, 0, 0},
    {JOY_EVENT_INPUT, 0, 10},

    {JOY_EVENT_INPUT, 0, 10},

    {JOY_EVENT_INPUT, BTN_START, 10},
    {JOY_EVENT_INPUT, 0, 20},
    {JOY_EVENT_INPUT, BTN_START, 10},
    {JOY_EVENT_INPUT, 0, 20},
    {JOY_EVENT_INPUT, BTN_DOWN, 10},
    {JOY_EVENT_INPUT, 0, 10},
    {JOY_EVENT_INPUT, BTN_DOWN, 10},
    {JOY_EVENT_INPUT, 0, 10},
    {JOY_EVENT_INPUT, BTN_START, 10},
    {JOY_EVENT_INPUT, 0, 20},
    {JOY_EVENT_INPUT, BTN_DOWN, 10},
    {JOY_EVENT_INPUT, 0, 10},
    {JOY_EVENT_INPUT, BTN_DOWN, 10},
    {JOY_EVENT_INPUT, 0, 10},
    {JOY_EVENT_INPUT, BTN_START, 10},
    {JOY_EVENT_INPUT, 0, 10},
    {JOY_EVENT_INPUT, 0, 1800},
    {JOY_EVENT_RESET, 0, 0},
    {JOY_EVENT_INPUT, 0, 10},
    {JOY_EVENT_INPUT, BTN_START, 10},
    {JOY_EVENT_INPUT, 0, 10}
};

static const int g_demo_count = sizeof(g_demo_events) / sizeof(g_demo_events[0]);
