@startuml
skinparam defaultFontName Linux Biolinum G
skinparam dpi 600
scale 1 as 120 pixels

concise "CPU" as CPU
concise "PPU" as PPU
concise "APU" as APU

@0
CPU is "N instrukcí"
PPU is {-}
APU is {-}

@1
CPU is {-}
PPU is Dohání
APU is {-}

@2
CPU is {-}
PPU is {-}
APU is Dohání

@3
CPU is "N instrukcí"
PPU is {-}
APU is {-}

@enduml
